import json,pathlib,hashlib,datetime,subprocess
p=pathlib.Path('/tmp/hrm-backup-real-392-validated.json');v=json.loads(p.read_text());a=v['backup']['attribution'];live=v['live'];proof=live['proof'];acl=proof['acl'];sha='392e0a38e37b9f3915e5ceb2d3b5caf8cd0698ad'
assert v['status']==live['status']=='READ_COMPLETE' and v['code'] is None and live['code'] is None
assert v['expectedMainSha']==v['productionArtifactSha']==live['expectedMainSha']==live['productionArtifactSha']==sha
assert v['cleanup']==live['cleanup']=='PASS'
assert v['backup']['protectedFileProfile']=='ROOT_BACKUP_0640' and v['backup']['databaseMatchesRuntime'] and v['backup']['declaredUserMatchesExpectedRole']
positive=['declaredRolePresent','separateFromRuntimeAndMigration','noSuperuser','bypassRls','canLogin','noCreateDb','noCreateRole','noInherit','noReplication','defaultReadOnly']
assert all(a[k] is True for k in positive)
assert all(a[k]==0 for k in ['outboundMemberships','inboundMemberships','setPrivilegedCount','otherWriteRows','otherGrantableRows'])
assert all(a[k]==1 for k in ['otherPrivilegeRows','matchedOtherPrivilegeRows','otherSelectRows','otherRecipientCount','matchedOtherRecipientCount'])
assert all(proof[k] is True for k in ['readOnlyBoth','repeatableReadBoth','expectedRuntimeSession','expectedMigrationSession','separatePrincipals','configuredHostsVerifiedLoopback','matchingPortAndDatabase','sameLiveDatabaseBackend','primaryBoth']) and proof['businessRowsRead'] is False
assert proof['runtimeProfile']=={'present':True,'noSuperuser':True,'noBypassRls':True,'canLogin':True,'setPrivilegedCount':0}
assert acl['explicitPrivilegeRows']==5 and acl['publicPrivilegeRows']==acl['grantableRows']==0 and acl['nonOwnerWriteRows']==3
assert {(e['recipient'],e['privilege'],e['scope'],e['grantable'],e['rowCount']) for e in acl['entries']}=={('EXPECTED_RUNTIME',p,'PUBLIC_SCHEMA',False,1) for p in ['SELECT','INSERT','UPDATE','DELETE']}|{('OTHER','SELECT','PUBLIC_SCHEMA',False,1)}
source=[]
for path in ['scripts/backup/bootstrap-backup-role.sql','scripts/backup/postgres-backup.sh','scripts/hrm-backup-acl-attribution.mjs','scripts/hrm-backup-acl-attribution.sql']:
 b=subprocess.check_output(['git','show',sha+':'+path]);assert b==pathlib.Path(path).read_bytes();source.append({'path':path,'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)})
result={'atUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'ROOT_SCOPED_DEFAULT_ACL_RECIPIENT_ASSESSED_ACCEPTABLE_PEER_PENDING','main':sha,'actualRun':37697340007,'actualArtifact':11516305817,'finiteArtifactSha256':hashlib.sha256(p.read_bytes()).hexdigest(),'assessment':'The sole OTHER public-schema default SELECT recipient is the statically declared protected backup identity, distinct from runtime and migration. Its observed catalog profile matches the existing explicit BYPASSRLS read-only backup contract. No OTHER writes/grant options/PUBLIC defaults/role membership/privileged SET path observed. Existing expected runtime SELECT/IUD defaults preserved. This resolves the previously unknown purpose of this specific extra default-ACL recipient without changing rights or weakening original gates.','sourceBindings':source,'originalGateStatusUnchanged':True,'productionMutation':False,'notProven':['Fresh backup authentication or commissioning','Backup service operation, dump integrity or restore','All existing object-level ACLs or schema CREATE privileges','C12 applied table constraints, physical/pilot/load acceptance','Future DDL quiet window or index timing','Live authenticated HR observations'],'limitations':'READ_COMPLETE alone is never approval. Nested old live-tool OTHER-unidentified limitation is superseded only for this one outer validated matched declared identity, not rewritten. Explicit default read-only catalog setting is observed, not forced migration read-only inference. Review is scoped to this known default ACL and existing source contract; old preflight INCOMPLETE results remain retained.'}
pathlib.Path('/tmp/hrm-backup-real-392-root-manual-assessment.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'status':result['status'],'extraRecipient':'DECLARED_BACKUP_SELECT_ONLY','roleProfile':'EXISTING_CONTRACT_MATCH','accessMutation':False}))
