// Entity field definitions for field-level permissions
// Field names MUST match actual Prisma schema column names.
// `label` is the English fallback; `labelKey` is the i18n key under the
// `fieldPermissions.*` namespace and is what the UI renders via t(labelKey).

export const ENTITY_FIELDS: Record<string, { name: string; label: string; labelKey: string; sensitive?: boolean }[]> = {
  company: [
    { name: "name", label: "Company Name", labelKey: "fieldPermissions.fieldCompanyName" },
    { name: "industry", label: "Industry", labelKey: "fieldPermissions.fieldIndustry" },
    { name: "phone", label: "Phone", labelKey: "fieldPermissions.fieldPhone", sensitive: true },
    { name: "email", label: "Email", labelKey: "fieldPermissions.fieldEmail", sensitive: true },
    { name: "website", label: "Website", labelKey: "fieldPermissions.fieldWebsite" },
    { name: "address", label: "Address", labelKey: "fieldPermissions.fieldAddress" },
    { name: "city", label: "City", labelKey: "fieldPermissions.fieldCity" },
    { name: "country", label: "Country", labelKey: "fieldPermissions.fieldCountry" },
    { name: "annualRevenue", label: "Annual Revenue", labelKey: "fieldPermissions.fieldAnnualRevenue", sensitive: true },
    { name: "employeeCount", label: "Employee Count", labelKey: "fieldPermissions.fieldEmployeeCount" },
    { name: "leadScore", label: "Lead Score", labelKey: "fieldPermissions.fieldLeadScore" },
    { name: "leadTemperature", label: "Lead Temperature", labelKey: "fieldPermissions.fieldLeadTemperature" },
    { name: "description", label: "Description", labelKey: "fieldPermissions.fieldDescription" },
    { name: "voen", label: "VOEN", labelKey: "fieldPermissions.fieldVoen", sensitive: true },
  ],
  contact: [
    { name: "fullName", label: "Full Name", labelKey: "fieldPermissions.fieldFullName" },
    { name: "email", label: "Email", labelKey: "fieldPermissions.fieldEmail", sensitive: true },
    { name: "phone", label: "Phone", labelKey: "fieldPermissions.fieldPhone", sensitive: true },
    { name: "position", label: "Position", labelKey: "fieldPermissions.fieldPosition" },
    { name: "department", label: "Department", labelKey: "fieldPermissions.fieldDepartment" },
    { name: "source", label: "Source", labelKey: "fieldPermissions.fieldSource" },
    { name: "tags", label: "Tags", labelKey: "fieldPermissions.fieldTags" },
    { name: "engagementScore", label: "Engagement Score", labelKey: "fieldPermissions.fieldEngagementScore" },
  ],
  deal: [
    { name: "name", label: "Deal Name", labelKey: "fieldPermissions.fieldDealName" },
    { name: "valueAmount", label: "Value", labelKey: "fieldPermissions.fieldValue", sensitive: true },
    { name: "currency", label: "Currency", labelKey: "fieldPermissions.fieldCurrency" },
    { name: "stage", label: "Stage", labelKey: "fieldPermissions.fieldStage" },
    { name: "probability", label: "Probability", labelKey: "fieldPermissions.fieldProbability" },
    { name: "expectedClose", label: "Expected Close Date", labelKey: "fieldPermissions.fieldExpectedCloseDate" },
    { name: "notes", label: "Notes", labelKey: "fieldPermissions.fieldNotes" },
    { name: "lostReason", label: "Loss Reason", labelKey: "fieldPermissions.fieldLossReason" },
    { name: "confidenceLevel", label: "Confidence Level", labelKey: "fieldPermissions.fieldConfidenceLevel" },
  ],
  contract: [
    { name: "title", label: "Title", labelKey: "fieldPermissions.fieldTitle" },
    { name: "contractNumber", label: "Contract Number", labelKey: "fieldPermissions.fieldContractNumber" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "valueAmount", label: "Value", labelKey: "fieldPermissions.fieldValue", sensitive: true },
    { name: "currency", label: "Currency", labelKey: "fieldPermissions.fieldCurrency" },
    { name: "startDate", label: "Start Date", labelKey: "fieldPermissions.fieldStartDate" },
    { name: "endDate", label: "End Date", labelKey: "fieldPermissions.fieldEndDate" },
    { name: "createdBy", label: "Created By", labelKey: "fieldPermissions.fieldCreatedBy" },
  ],
  invoice: [
    { name: "invoiceNumber", label: "Invoice Number", labelKey: "fieldPermissions.fieldInvoiceNumber" },
    { name: "title", label: "Title", labelKey: "fieldPermissions.fieldTitle" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "totalAmount", label: "Total Amount", labelKey: "fieldPermissions.fieldTotalAmount", sensitive: true },
    { name: "balanceDue", label: "Balance Due", labelKey: "fieldPermissions.fieldBalanceDue", sensitive: true },
    { name: "currency", label: "Currency", labelKey: "fieldPermissions.fieldCurrency" },
    { name: "dueDate", label: "Due Date", labelKey: "fieldPermissions.fieldDueDate" },
    { name: "companyId", label: "Company", labelKey: "fieldPermissions.fieldCompany" },
  ],
  bill: [
    { name: "billNumber", label: "Bill Number", labelKey: "fieldPermissions.fieldBillNumber" },
    { name: "vendorName", label: "Vendor", labelKey: "fieldPermissions.fieldVendor" },
    { name: "title", label: "Title", labelKey: "fieldPermissions.fieldTitle" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "totalAmount", label: "Total Amount", labelKey: "fieldPermissions.fieldTotalAmount", sensitive: true },
    { name: "balanceDue", label: "Balance Due", labelKey: "fieldPermissions.fieldBalanceDue", sensitive: true },
    { name: "currency", label: "Currency", labelKey: "fieldPermissions.fieldCurrency" },
    { name: "dueDate", label: "Due Date", labelKey: "fieldPermissions.fieldDueDate" },
    { name: "category", label: "Category", labelKey: "fieldPermissions.fieldCategory" },
  ],
  payment_order: [
    { name: "orderNumber", label: "Payment Order Number", labelKey: "fieldPermissions.fieldPaymentOrderNumber" },
    { name: "counterpartyName", label: "Counterparty", labelKey: "fieldPermissions.fieldCounterparty" },
    { name: "amount", label: "Amount", labelKey: "fieldPermissions.fieldAmount", sensitive: true },
    { name: "currency", label: "Currency", labelKey: "fieldPermissions.fieldCurrency" },
    { name: "purpose", label: "Purpose", labelKey: "fieldPermissions.fieldPurpose" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "createdBy", label: "Created By", labelKey: "fieldPermissions.fieldCreatedBy" },
    { name: "approvedBy", label: "Approved By", labelKey: "fieldPermissions.fieldApprovedBy" },
  ],
  offer: [
    { name: "offerNumber", label: "Offer Number", labelKey: "fieldPermissions.fieldOfferNumber" },
    { name: "title", label: "Title", labelKey: "fieldPermissions.fieldTitle" },
    { name: "clientName", label: "Client", labelKey: "fieldPermissions.fieldClient" },
    { name: "totalAmount", label: "Total Amount", labelKey: "fieldPermissions.fieldTotalAmount", sensitive: true },
    { name: "currency", label: "Currency", labelKey: "fieldPermissions.fieldCurrency" },
    { name: "validUntil", label: "Valid Until", labelKey: "fieldPermissions.fieldValidUntil" },
  ],
  quote: [
    { name: "quoteNumber", label: "Quote Number", labelKey: "fieldPermissions.fieldQuoteNumber" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "customerName", label: "Customer", labelKey: "fieldPermissions.fieldCustomer" },
    { name: "totalAmount", label: "Total Amount", labelKey: "fieldPermissions.fieldTotalAmount", sensitive: true },
    { name: "currency", label: "Currency", labelKey: "fieldPermissions.fieldCurrency" },
    { name: "validUntil", label: "Valid Until", labelKey: "fieldPermissions.fieldValidUntil" },
  ],
  campaign: [
    { name: "name", label: "Campaign Name", labelKey: "fieldPermissions.fieldCampaignName" },
    { name: "type", label: "Channel", labelKey: "fieldPermissions.fieldChannel" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "totalSent", label: "Sent", labelKey: "fieldPermissions.fieldTotalSent" },
    { name: "totalOpened", label: "Opened", labelKey: "fieldPermissions.fieldTotalOpened" },
    { name: "totalClicked", label: "Clicked", labelKey: "fieldPermissions.fieldTotalClicked" },
  ],
  mtm_route: [
    { name: "name", label: "Route Name", labelKey: "fieldPermissions.fieldRouteName" },
    { name: "agentId", label: "Agent", labelKey: "fieldPermissions.fieldAgent" },
    { name: "date", label: "Date", labelKey: "fieldPermissions.fieldDate" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "totalPoints", label: "Total Points", labelKey: "fieldPermissions.fieldTotalPoints" },
    { name: "visitedPoints", label: "Visited Points", labelKey: "fieldPermissions.fieldVisitedPoints" },
    { name: "startedAt", label: "Started At", labelKey: "fieldPermissions.fieldStartedAt" },
    { name: "completedAt", label: "Completed At", labelKey: "fieldPermissions.fieldCompletedAt" },
    { name: "notes", label: "Notes", labelKey: "fieldPermissions.fieldNotes" },
  ],
  mtm_visit: [
    { name: "agentId", label: "Agent", labelKey: "fieldPermissions.fieldAgent" },
    { name: "customerId", label: "Customer", labelKey: "fieldPermissions.fieldCustomer" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "checkInAt", label: "Check-in Time", labelKey: "fieldPermissions.fieldCheckInAt" },
    { name: "checkOutAt", label: "Check-out Time", labelKey: "fieldPermissions.fieldCheckOutAt" },
    { name: "duration", label: "Duration", labelKey: "fieldPermissions.fieldDuration" },
    { name: "notes", label: "Notes", labelKey: "fieldPermissions.fieldNotes" },
    { name: "tasksCompleted", label: "Tasks Completed", labelKey: "fieldPermissions.fieldTasksCompleted" },
    { name: "tasksTotal", label: "Tasks Total", labelKey: "fieldPermissions.fieldTasksTotal" },
  ],
  mtm_photo: [
    { name: "agentId", label: "Agent", labelKey: "fieldPermissions.fieldAgent" },
    { name: "visitId", label: "Visit", labelKey: "fieldPermissions.fieldVisit" },
    { name: "url", label: "Photo URL", labelKey: "fieldPermissions.fieldPhotoUrl", sensitive: true },
    { name: "thumbnailUrl", label: "Thumbnail URL", labelKey: "fieldPermissions.fieldThumbnailUrl", sensitive: true },
    { name: "category", label: "Category", labelKey: "fieldPermissions.fieldCategory" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "hasWatermark", label: "Watermark", labelKey: "fieldPermissions.fieldWatermark" },
    { name: "reviewedBy", label: "Reviewed By", labelKey: "fieldPermissions.fieldReviewedBy" },
    { name: "reviewedAt", label: "Reviewed At", labelKey: "fieldPermissions.fieldReviewedAt" },
    { name: "reviewNote", label: "Review Note", labelKey: "fieldPermissions.fieldReviewNote" },
  ],
  lead: [
    { name: "contactName", label: "Lead Name", labelKey: "fieldPermissions.fieldLeadName" },
    { name: "email", label: "Email", labelKey: "fieldPermissions.fieldEmail", sensitive: true },
    { name: "phone", label: "Phone", labelKey: "fieldPermissions.fieldPhone", sensitive: true },
    { name: "companyName", label: "Company", labelKey: "fieldPermissions.fieldCompany" },
    { name: "estimatedValue", label: "Estimated Value", labelKey: "fieldPermissions.fieldEstimatedValue", sensitive: true },
    { name: "score", label: "Score", labelKey: "fieldPermissions.fieldScore" },
    { name: "source", label: "Source", labelKey: "fieldPermissions.fieldSource" },
    { name: "notes", label: "Notes", labelKey: "fieldPermissions.fieldNotes" },
  ],
  ticket: [
    { name: "subject", label: "Subject", labelKey: "fieldPermissions.fieldSubject" },
    { name: "description", label: "Description", labelKey: "fieldPermissions.fieldDescription" },
    { name: "priority", label: "Priority", labelKey: "fieldPermissions.fieldPriority" },
    { name: "category", label: "Category", labelKey: "fieldPermissions.fieldCategory" },
    { name: "tags", label: "Tags", labelKey: "fieldPermissions.fieldTags" },
    { name: "satisfactionRating", label: "CSAT Rating", labelKey: "fieldPermissions.fieldCsatRating" },
  ],
  task: [
    { name: "title", label: "Title", labelKey: "fieldPermissions.fieldTitle" },
    { name: "description", label: "Description", labelKey: "fieldPermissions.fieldDescription" },
    { name: "status", label: "Status", labelKey: "fieldPermissions.fieldStatus" },
    { name: "priority", label: "Priority", labelKey: "fieldPermissions.fieldPriority" },
    { name: "dueDate", label: "Due Date", labelKey: "fieldPermissions.fieldDueDate" },
    { name: "assignedTo", label: "Assigned To", labelKey: "fieldPermissions.fieldAssignedTo" },
    { name: "relatedType", label: "Related Entity Type", labelKey: "fieldPermissions.fieldRelatedEntityType" },
    { name: "relatedId", label: "Related Entity ID", labelKey: "fieldPermissions.fieldRelatedEntityId" },
    // Optional FK to a Project for rollup contribution. See
    // `src/lib/project-rollup.ts` and Phase 2 of the Notion-tasks plan.
    { name: "projectId", label: "Project", labelKey: "fieldPermissions.fieldProject" },
    // customFields is a JSONB column; permission is all-or-nothing for the
    // whole object (no per-key). See docs/rbac-custom-fields.md for details.
    { name: "customFields", label: "Custom Fields", labelKey: "fieldPermissions.fieldCustomFields" },
  ],
  activity: [
    { name: "type", label: "Activity Type", labelKey: "fieldPermissions.fieldActivityType" },
    { name: "subject", label: "Subject", labelKey: "fieldPermissions.fieldSubject" },
    { name: "description", label: "Description", labelKey: "fieldPermissions.fieldDescription" },
    { name: "contactId", label: "Contact", labelKey: "fieldPermissions.fieldContact" },
    { name: "companyId", label: "Company", labelKey: "fieldPermissions.fieldCompany" },
    { name: "relatedType", label: "Related Entity Type", labelKey: "fieldPermissions.fieldRelatedEntityType" },
    { name: "relatedId", label: "Related Entity ID", labelKey: "fieldPermissions.fieldRelatedEntityId" },
    { name: "scheduledAt", label: "Scheduled At", labelKey: "fieldPermissions.fieldScheduledAt" },
    { name: "completedAt", label: "Completed At", labelKey: "fieldPermissions.fieldCompletedAt" },
  ],
}

export const ENTITY_TYPES = Object.keys(ENTITY_FIELDS)
