/**
 * Azerbaijani copy for the guided-demo chrome (guide panel, coach mark,
 * header). Product screens inside the scenes use the product's own
 * `messages/az.json` through next-intl; only the demo's own layer lives here.
 */
export const DEMO_JOURNEY_STRINGS = {
  sectionAria: "LeadDrive bələdçili demo",
  badgePrivate: "Məxfi demo",
  badgePreview: "Admin ön baxışı",
  forCompany: (company: string) => `Yalnız ${company} üçün hazırlanıb`,
  forCompanyPreview: (company: string) => `${company} üçün müştəri görünüşü`,
  progressAria: "Demo irəliləyişi",
  steps: (done: number, total: number) => `${done} / ${total} addım`,
  sessionIdle: "Fasilə",
  sessionAbsolute: "Sessiya",
  sessionIdleTitle: "Fəaliyyətsizlik limiti",
  sessionAbsoluteTitle: "Sessiyanın mütləq limiti",
  sidebarAria: "Demo naviqasiyası",
  notReachable: "Bu bölməyə hələ gəlməmisiniz",
  guide: "Bələdçi",
  sectionOf: (index: number, total: number) => `Bölmə ${index} / ${total}`,
  minutes: (minutes: number) => `~${minutes} dəq`,
  stepOf: (index: number, total: number) => `Addım ${index} / ${total}`,
  next: "İrəli",
  back: "Geri",
  skip: "Keç",
  observe: "Baxın",
  waiting: "Hərəkət gözlənilir",
  stepOnScene: "Bu addım ekranda göstərilir",
  resultTitle: "Nəticə",
  anchorMissingTitle: "Element ekranda tapılmadı",
  anchorMissingBody: "Bu addımın göstərməli olduğu element hazırda görünmür. Bələdçidən davam edə bilərsiniz.",
  continueFromGuide: "Bələdçidən davam et",
  reviewMode: "Baxış rejimi",
  reviewBody: "Keçdiyiniz bölməyə baxırsınız. Hekayə cari addımda gözləyir.",
  backToCurrent: "Cari addıma qayıt",
  hintFollow: (stepTitle: string) => `Bələdçidəki addımı izləyin: ${stepTitle}`,
  hintDisabled: "Bu demoda mövcud deyil",
  clipTitle: "Qısa klip",
  clipPlanned: "Klip hazırlanır",
  clipPlay: "Klipi izlə",
  assistantTitle: "Da Vinci-dən soruşun",
  assistantOff: "Köməkçi bu sessiyada deaktivdir",
  assistantPlaceholder: "Bu ekran haqqında sualınızı yazın…",
  assistantAsk: "Soruş",
  assistantAsking: "Soruşulur…",
  assistantFailed: "Köməkçi cavab vermədi. Bir az sonra yenidən cəhd edin.",
  assistantRemaining: (left: number) => `${left} sual qalıb`,
  assistantPreviewOnly: "Admin ön baxışında köməkçi sual qəbul etmir — o, müştərinin canlı sessiyasında işləyir.",
  assistantOpenDemo: "Köməkçi açıq demoda söndürülüb. Şəxsi demo istəyin — orada suallarınıza cavab verir.",
  clipOpenDemo: "Video şəxsi demoda açılır. Bələdçi mətni burada hər addımı izah edir.",
  badgeOpen: "Açıq demo",
  openIntro: "Bu, LeadDrive-ın real interfeysidir. Qeydlər nümunədir, heç nə göndərilmir.",
  openNameLabel: "Adınız",
  openCompanyLabel: "Şirkətiniz",
  openStart: "Demonu aç",
  openPersonalise: "İstəsəniz, adınızı və şirkətinizi yazın — hekayədəki lid siz olacaqsınız.",
  openPrivateCta: "Şəxsi demo istəyin",
  openPrivateNote: "Şəxsi demoda köməkçi və video da açılır.",
  pendingSceneTitle: "Səhnə hazırlanır",
  pendingSceneBody: (title: string) =>
    `«${title}» səhnəsi növbəti mərhələdə real LeadDrive ekranı üzərində qurulacaq. Bu bildiriş yalnız admin ön baxışında görünür.`,
  completedTitle: "Demo tamamlandı",
  completedBody: "Sessiya bağlandı və link bir daha işləməyəcək. Davamı üçün satış komandası ilə əlaqə saxlayın.",
  contactSales: "Satış komandası ilə əlaqə",
  finish: "Bitir",
  syntheticNote: "Bütün qeydlər nümunədir və sessiya bitəndə silinir.",
  welcome: (name: string) => `Salam, ${name}!`,
  welcomeBody: (company: string) =>
    `Bu, LeadDrive-ın real interfeysidir. İndi ${company} üçün bir hekayəni birlikdə keçəcəyik: müraciətdən qazanılmış sövdələşməyə qədər.`,
  welcomePoints: [
    "Solda — yalnız bu demo üçün açılmış dörd bölmə.",
    "Sağda — bələdçi: hər addımda nə etməli olduğunuzu göstərir.",
    "Hər addım yalnız real hərəkətdən sonra tamamlanmış sayılır.",
  ],
  summaryDone: "Tamamlandı",
  summarySkipped: "Keçildi",
  summaryAttribution: (campaign: string, amount: string) => `Mənbə «${campaign}» → qazanılmış sövdələşmə ${amount}`,
  demoButtonHint: "Bu düymə demoda simulyasiya edilir",
  simulatedSend: "simulyasiya",
  aiDraftTitle: "AI qaralaması — yoxlama tələb olunur",
  aiDraftQuality: (score: number) => `keyfiyyət ${score}`,
  aiDraftReason: "Yalnız qaralama rejimi: cavabı operator təsdiqləməyincə göndərilmir.",
  aiDraftDiscard: "İmtina et",
  linkedLead: "Bağlı lid",
  boardsTitle: "Lövhələr",
  salesBoard: "Satış lövhəsi",
  boardReportsTab: "Hesabatlar",
  boardBoardTab: "Lövhə",
  boardMine: "Mənim",
  boardCreatedByMe: "Mən yaratdım",
  boardReportsEmpty: "Bir tapşırıqla hesabatlar demək olar ki, boşdur — real komandada burada günün mənzərəsi görünür.",
  taskDueTomorrow: "Sabah",
  quoteVat: "ƏDV",
  quoteNet: "Cəm",
  quoteGross: "Yekun",
  quoteValidUntil: "Etibarlıdır",
  dealProbability: "Ehtimal",
  dealAmount: "Məbləğ",
  dealExpectedClose: "Gözlənilən bağlanma",
  dealOwner: "Məsul",
  dragHint: "Növbəti mərhələyə keçir",
  nextBestOffers: "Uyğun təkliflər",
  nextBestOffersBody: "10 istifadəçilik paket və Omni-Channel modulu — bu ölçüdə komandalar adətən bunu seçir.",
  aiPrediction: "AI proqnozu",
  aiPredictionBody: "Nümunə hesablama: cavab sürəti və müraciətin konkretliyi nəzərə alınıb.",
  liveCallTitle: "Real AI zəngi",
  liveCallIntro: "Zəng yalnız sorğuda göstərdiyiniz nömrəyə edilir: ona SMS kodu göndəririk, siz təsdiqləyirsiniz və LeadDrive-ın AI köməkçisi sizə zəng edir.",
  liveCallUseRequestPhone: "Sorğudakı nömrəyə kod göndər",
  liveCallNoRequestPhone: "Sorğunuzda Azərbaycan mobil nömrəsi göstərilməyib, zəng isə yalnız həmin nömrəyə edilir. Hekayəyə zəngsiz davam edə bilərsiniz.",
  liveCallCodeLabel: "SMS kodu",
  liveCallVerify: "Təsdiqlə",
  liveCallConsentRequired: "Zəngə razılığınızı qeyd edin",
  liveCallVerified: "Nömrə təsdiqləndi",
  liveCallCallNow: "Zəng et",
  liveCallQueued: "Zəng hazırlanır…",
  liveCallCalling: "Zəng edilir — telefonunuza baxın.",
  liveCallDecline: "Zəngsiz davam et",
  liveCallRetry: "Yenidən cəhd et",
  liveCallContinue: "Davam et",
  liveCallTooLong: "Zəngin nəticəsi hələ gəlmədi. Menecer vəziyyəti dəqiqləşdirəcək — hekayəyə davam edə bilərsiniz.",
  liveCallFailed: "Sorğu alınmadı. Bir az sonra yenidən cəhd edin.",
  liveCallRules: "Demoda zəng bir dəfə edilir və ən çoxu iki dəqiqə çəkir.",
  liveCallOnlyOnce: "Bu demoda zəng yalnız bir dəfə edilir — sizin zənginiz artıq sifariş olunub. Nəticəni burada görəcəksiniz.",
  aiSuggestion: "Növbəti addım",
  aiSuggestionBody: "Təklifi hazırlayın və etibarlılıq müddətini 14 günlə məhdudlaşdırın — qərar sürətlənir.",
} as const
