/**
 * Azerbaijani copy for the guided-demo chrome (guide panel, coach mark,
 * header). Product screens inside the scenes use the product's own
 * `messages/az.json` through next-intl; only the demo's own layer lives here.
 */
export const DEMO_JOURNEY_STRINGS = {
  sectionAria: "LeadDrive bələdçili demo",
  badgePrivate: "Məxfi demo",
  badgePreview: "Admin ön baxışı",
  forCompany: (company: string) => `Yalnız ${company} üçün hazırlanıb`,
  forCompanyPreview: (company: string) => `${company} üçün müştəri görünüşü`,
  progressAria: "Demo irəliləyişi",
  steps: (done: number, total: number) => `${done} / ${total} addım`,
  sessionIdle: "Fasilə",
  sessionAbsolute: "Sessiya",
  sessionIdleTitle: "Fəaliyyətsizlik limiti",
  sessionAbsoluteTitle: "Sessiyanın mütləq limiti",
  sidebarAria: "Demo naviqasiyası",
  notReachable: "Bu bölməyə hələ gəlməmisiniz",
  guide: "Bələdçi",
  sectionOf: (index: number, total: number) => `Bölmə ${index} / ${total}`,
  minutes: (minutes: number) => `~${minutes} dəq`,
  stepOf: (index: number, total: number) => `Addım ${index} / ${total}`,
  next: "İrəli",
  back: "Geri",
  skip: "Keç",
  observe: "Baxın",
  waiting: "Hərəkət gözlənilir",
  resultTitle: "Nəticə",
  anchorMissingTitle: "Element ekranda tapılmadı",
  anchorMissingBody: "Bu addımın göstərməli olduğu element hazırda görünmür. Bələdçidən davam edə bilərsiniz.",
  continueFromGuide: "Bələdçidən davam et",
  reviewMode: "Baxış rejimi",
  reviewBody: "Keçdiyiniz bölməyə baxırsınız. Hekayə cari addımda gözləyir.",
  backToCurrent: "Cari addıma qayıt",
  hintFollow: (stepTitle: string) => `Bələdçidəki addımı izləyin: ${stepTitle}`,
  hintDisabled: "Bu demoda mövcud deyil",
  clipTitle: "Qısa klip",
  clipPlanned: "Klip hazırlanır",
  clipUnavailableHere: "Video bu sessiyada açılmır — bələdçi mətni hər addımı izah edir.",
  clipPlay: "Klipi izlə",
  assistantTitle: "Da Vinci-dən soruşun",
  assistantOff: "Köməkçi bu sessiyada deaktivdir",
  pendingSceneTitle: "Səhnə hazırlanır",
  pendingSceneBody: (title: string) =>
    `«${title}» səhnəsi növbəti mərhələdə real LeadDrive ekranı üzərində qurulacaq. Bu bildiriş yalnız admin ön baxışında görünür.`,
  completedTitle: "Demo tamamlandı",
  completedBody: "Sessiya bağlandı və link bir daha işləməyəcək. Davamı üçün satış komandası ilə əlaqə saxlayın.",
  contactSales: "Satış komandası ilə əlaqə",
  finish: "Bitir",
  syntheticNote: "Bütün qeydlər nümunədir və sessiya bitəndə silinir.",
  welcome: (name: string) => `Salam, ${name}!`,
  welcomeBody: (company: string) =>
    `Bu, LeadDrive-ın real interfeysidir. İndi ${company} üçün bir hekayəni birlikdə keçəcəyik: müraciətdən qazanılmış sövdələşməyə qədər.`,
  welcomePoints: [
    "Solda — yalnız bu demo üçün açılmış dörd bölmə.",
    "Sağda — bələdçi: hər addımda nə etməli olduğunuzu göstərir.",
    "Hər addım yalnız real hərəkətdən sonra tamamlanmış sayılır.",
  ],
  summaryDone: "Tamamlandı",
  summarySkipped: "Keçildi",
  summaryAttribution: (campaign: string, amount: string) => `Mənbə «${campaign}» → qazanılmış sövdələşmə ${amount}`,
  demoButtonHint: "Bu düymə demoda simulyasiya edilir",
  simulatedSend: "simulyasiya",
  aiDraftTitle: "AI qaralaması — yoxlama tələb olunur",
  aiDraftQuality: (score: number) => `keyfiyyət ${score}`,
  aiDraftReason: "Yalnız qaralama rejimi: cavabı operator təsdiqləməyincə göndərilmir.",
  aiDraftDiscard: "İmtina et",
  linkedLead: "Bağlı lider",
  boardsTitle: "Lövhələr",
  salesBoard: "Satış lövhəsi",
  boardReportsTab: "Hesabatlar",
  boardBoardTab: "Lövhə",
  boardMine: "Mənim",
  boardCreatedByMe: "Mən yaratdım",
  boardReportsEmpty: "Bir tapşırıqla hesabatlar demək olar ki, boşdur — real komandada burada günün mənzərəsi görünür.",
  taskDueTomorrow: "Sabah",
  quoteVat: "ƏDV",
  quoteNet: "Cəm",
  quoteGross: "Yekun",
  quoteValidUntil: "Etibarlıdır",
  dealProbability: "Ehtimal",
  dealAmount: "Məbləğ",
  dealExpectedClose: "Gözlənilən bağlanma",
  dealOwner: "Məsul",
  dragHint: "Növbəti mərhələyə keçir",
  nextBestOffers: "Uyğun təkliflər",
  nextBestOffersBody: "10 istifadəçilik paket və Omni-Channel modulu — bu ölçüdə komandalar adətən bunu seçir.",
  aiPrediction: "AI proqnozu",
  aiPredictionBody: "Nümunə hesablama: cavab sürəti və müraciətin konkretliyi nəzərə alınıb.",
  aiSuggestion: "Növbəti addım",
  aiSuggestionBody: "Təklifi hazırlayın və etibarlılıq müddətini 14 günlə məhdudlaşdırın — qərar sürətlənir.",
} as const
