#!/usr/bin/env bash
set -Eeuo pipefail
: "${DEPLOY_TARGET_SHA:?}"
export GITHUB_WORKSPACE="$PWD"
# Assemble standalone bundle
mkdir -p .next/standalone/.next
cp -r .next/static .next/standalone/.next/static

MANIFEST_COPIED=0
while IFS= read -r src; do
  rel="${src#.next/server/}"
  dest=".next/standalone/.next/server/${rel}"
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  MANIFEST_COPIED=$((MANIFEST_COPIED + 1))
done < <(find .next/server/app -name '*_client-reference-manifest.js')
echo "::notice::Copied $MANIFEST_COPIED client-reference-manifest file(s)"
if [ -f ".next/server/app/(dashboard)/social-monitoring/page_client-reference-manifest.js" ] \
   && [ ! -f ".next/standalone/.next/server/app/(dashboard)/social-monitoring/page_client-reference-manifest.js" ]; then
  echo "::error::social-monitoring client-reference-manifest missing from standalone"
  exit 1
fi

mkdir -p .next/standalone/node_modules
cp -r node_modules/.prisma .next/standalone/node_modules/.prisma
cp -r node_modules/@prisma .next/standalone/node_modules/@prisma

mkdir -p .next/standalone/public
cp -r public/. .next/standalone/public/

# The service worker is GENERATED by @serwist/next during the build
# (swDest: public/sw.js) and is gitignored, so a build that quietly
# skips serwist — as the turbopack build did from 2026-08-02 — ships an
# artifact with no worker at all and /sw.js starts answering 404
# everywhere. That takes Web Push and the /offline shell down without
# failing anything, which is exactly why it went unnoticed. Assert it.
if [ ! -f .next/standalone/public/sw.js ]; then
  echo "::error::public/sw.js missing from the standalone artifact — @serwist/next did not run (webpack-only; check the build flags)"
  exit 1
fi
echo "::notice::Service worker staged ($(wc -c < .next/standalone/public/sw.js) bytes)"

if [ -d video/player ]; then
  mkdir -p .next/standalone/help-videos/player
  cp -r video/player/. .next/standalone/help-videos/player/
  HELP_VIDEO_ASSET_VERSION="$(
    sed -nE 's/^const HELP_VIDEO_ASSET_VERSION = "([^"]+)"$/\1/p' \
      src/content/help/video-assets.ts
  )"
  [ -n "$HELP_VIDEO_ASSET_VERSION" ] || {
    echo "::error::Could not read HELP_VIDEO_ASSET_VERSION"
    exit 1
  }
  printf '%s\n' "$HELP_VIDEO_ASSET_VERSION" > .next/standalone/help-videos/asset-version
fi

cp -r prisma .next/standalone/prisma

mkdir -p .next/standalone/scripts
cp -r scripts/*.mjs .next/standalone/scripts/ 2>/dev/null || true
cp -r scripts/*.ts  .next/standalone/scripts/ 2>/dev/null || true
cp -r scripts/*.sh  .next/standalone/scripts/ 2>/dev/null || true
cp scripts/event-platform-postconditions.sql .next/standalone/scripts/
test -s .next/standalone/scripts/event-platform-postconditions.sql || {
  echo "::error::event-platform production postcondition missing from standalone artifact"
  exit 1
}
test -s .next/standalone/scripts/event-platform-legacy-client-probe.mjs || {
  echo "::error::event-platform legacy-client probe missing from standalone artifact"
  exit 1
}
CRON_SCRIPT_ALLOWLIST="ops/cron/release-script-allowlist.txt"
test -s "$CRON_SCRIPT_ALLOWLIST" || {
  echo "::error::release cron-script allowlist is empty"
  exit 1
}
LC_ALL=C sort -cu "$CRON_SCRIPT_ALLOWLIST" || {
  echo "::error::release cron-script allowlist must be sorted and unique"
  exit 1
}
while IFS= read -r script; do
  [[ "$script" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*\.sh$ ]] || {
    echo "::error::unsafe cron script allowlist entry: $script"
    exit 1
  }
  test -x "scripts/$script" || {
    echo "::error::release cron script missing or not executable: $script"
    exit 1
  }
done < "$CRON_SCRIPT_ALLOWLIST"
cp "$CRON_SCRIPT_ALLOWLIST" .next/standalone/scripts/release-cron-script-manifest.txt
mkdir -p .next/standalone/scripts/seeds
cp -r scripts/seeds/*.mjs .next/standalone/scripts/seeds/ 2>/dev/null || true

# Backup, log-shipping and secret-snapshot jobs are release-owned
# operational code. They used to be scp'd into the stale checkout,
# which both hid the reviewed version and made `git status` dirty on
# every release. Bundle them beside the artifact instead.
mkdir -p .next/standalone/scripts/backup
cp -r scripts/backup/. .next/standalone/scripts/backup/
for file in hash-recovery-db-contract.sh hash-recovery-program-set.sh postgres-backup.sh postgres-restore-canary.sh prove-source-database.sh ship-logs.sh snapshot-runtime-files.sh snapshot-secrets.sh; do
  test -x ".next/standalone/scripts/backup/$file" || {
    echo "::error::release-owned backup script missing: $file"
    exit 1
  }
done
scripts/backup/hash-recovery-db-contract.sh --manifest "$GITHUB_WORKSPACE" \
  >.next/standalone/scripts/backup/recovery-db-contract.tsv
test "$(sha256sum .next/standalone/scripts/backup/recovery-db-contract.tsv | awk '{print $1}')" = \
  "$(.next/standalone/scripts/backup/hash-recovery-db-contract.sh .next/standalone)" || {
  echo "::error::release recovery DB contract manifest differs from Prisma schema/migrations"
  exit 1
}

# Unit/logrotate definitions are installed by server-deploy.sh only
# after the app health check passes. Keeping them in the same
# immutable artifact prevents a source-checkout copy from drifting.
mkdir -p .next/standalone/ops/backup .next/standalone/ops/systemd .next/standalone/ops/logrotate
cp -r ops/backup/. .next/standalone/ops/backup/
cp -r ops/systemd/. .next/standalone/ops/systemd/
cp -r ops/logrotate/. .next/standalone/ops/logrotate/
for file in \
  leaddrive-log-ship.service \
  leaddrive-log-ship.timer \
  leaddrive-postgres-backup.service \
  leaddrive-postgres-backup.timer \
  leaddrive-runtime-files-snapshot.service \
  leaddrive-runtime-files-snapshot.timer \
  leaddrive-secrets-snapshot.service \
  leaddrive-secrets-snapshot.timer; do
  test -f ".next/standalone/ops/systemd/$file" || {
    echo "::error::release-owned systemd unit missing: $file"
    exit 1
  }
done
for file in leaddrive-v2 leaddrive-cron-logs; do
  test -f ".next/standalone/ops/logrotate/$file" || {
    echo "::error::release-owned logrotate definition missing: $file"
    exit 1
  }
done
test -f .next/standalone/ops/backup/backup.env.example
test -f .next/standalone/ops/backup/recovery-program-set.files

# The RLS maintenance scripts run ON PRODUCTION, against the live
# database, as the BYPASSRLS migration role — `cleanup-orphan-tenant-rows.sql`
# DELETEs rows. The globs above match only the top level of scripts/,
# so this whole directory was missing from every release and had to be
# scp'd by hand. That is the dangerous part: a deploy wipes and
# re-extracts standalone, so hand-delivered copies disappear at the
# next deploy and the runbook command silently resolves against
# $APP_DIR's git checkout instead — on 2026-08-28 that checkout was 11
# days stale, held a different enable-batch-4.sql, and did not contain
# the cleanup script at all. Shipping the directory with the release
# makes the copy on the box the copy that was reviewed.
#
# Whole subdirectory, not just *.sql: enable-one.sh and
# verify-coverage.mjs are documented as server-side helpers too
# (docs/rls-core-tables-runbook.md), and an extension list is exactly
# what failed here. No secrets — these are DDL and catalog queries;
# the credential stays in /etc/leaddrive/migration.env (root, 0600).
#
# Asserted rather than `|| true`, like the relay above: this can only
# fail if the directory is renamed or removed, and that is a change
# whose author should be told, in CI, before the artifact is staged.
mkdir -p .next/standalone/scripts/rls
cp -r scripts/rls/. .next/standalone/scripts/rls/
if [ ! -f .next/standalone/scripts/rls/cleanup-orphan-tenant-rows.sql ]; then
  echo "::error::RLS maintenance scripts missing from the standalone artifact"
  exit 1
fi

# The softphone relay is a long-running pm2 app, not a maintenance
# script, so unlike everything above it MUST be here or the deploy
# fails outright: pm2 starts every app in the ecosystem file and a
# missing script file is a non-zero exit for the whole start. That is
# exactly what happened on 2026-08-24 - the globs above only match
# scripts/ at the top level, the relay lives in a subdirectory, and
# production rolled back after the swap.
#
# Staged with an explicit assertion rather than the `|| true` used for
# optional helpers: a relay silently absent means every browser call
# reaches an answered customer and then finds nobody to join them to.
mkdir -p .next/standalone/scripts/softphone-relay
cp -r scripts/softphone-relay/. .next/standalone/scripts/softphone-relay/
if [ ! -f .next/standalone/scripts/softphone-relay/relay.mjs ]; then
  echo "::error::softphone relay missing from the standalone artifact"
  exit 1
fi

# `ws` is the relay's only non-builtin import, and Next traces only
# what the WEB app imports - which is not this. Copied beside the
# other hand-staged runtime deps so resolution cannot depend on the
# server happening to still have a repo checkout at /opt.
cp -r node_modules/ws .next/standalone/node_modules/ws
if [ ! -d .next/standalone/node_modules/ws ]; then
  echo "::error::ws missing from the standalone artifact — the relay cannot start"
  exit 1
fi

cp ecosystem.config.cjs .next/standalone/ecosystem.config.cjs
[[ "$DEPLOY_TARGET_SHA" =~ ^[0-9a-f]{40}$ ]] || {
  echo "::error::DEPLOY_TARGET_SHA is not a full commit SHA"
  exit 1
}
printf '%s\n' "$DEPLOY_TARGET_SHA" > .next/standalone/.deploy-sha
[ ! -e .next/standalone/.event-platform-fund-atomic-insert-first-v1 ] \
  && [ ! -L .next/standalone/.event-platform-fund-atomic-insert-first-v1 ] || {
  echo "::error::final artifact must not claim the one-release Fund atomic prerequisite contract"
  exit 1
}

# Create deployment tarball
cd .next/standalone
test "$(tr -d '\r\n' < .deploy-sha)" = "$DEPLOY_TARGET_SHA"
tar -czf "/tmp/leaddrive-prod-${DEPLOY_TARGET_SHA}.tar.gz" .
echo "::notice::Tarball size: $(du -h "/tmp/leaddrive-prod-${DEPLOY_TARGET_SHA}.tar.gz" | cut -f1)"
