/**
 * Log only a fixed operation label for sensitive Workforce failures.
 * Never pass an error object, message, case reference, or employee input.
 */
export function logWorkforceSensitiveOperationFailure(input: {
  operation:
    | "auth-workforce-grant-management"
    | "review-exception-decision-write"
    | "review-exception-response-write"
    | "review-workday-correction"
    | "review-workday-reopen"
    | "review-workday-reopen-undo"
    | "review-timesheet-approval-export"
    | "preview-timesheet-approval-export"
    | "authorize-approved-timesheet-report"
    | "read-approved-timesheet-report"
    | "read-exception-case-report"
    | "authorize-site-transition-report"
    | "read-site-transition-report"
    | "authorize-evidence-timeline"
    | "authorize-evidence-directory"
    | "read-evidence-timeline"
    | "search-evidence-timeline-targets"
    | "retention-raw-location-dry-run"
    | "verify-attendance-mfa"
    | "verify-attendance-administration"
    | "configuration-access-lookup"
    | "configuration-access-grant-write"
    | "configuration-access-grant-inventory"
    | "configuration-access-grant-target-search"
    | "configuration-access-review"
    | "configuration-exception-response-cycle-audit"
  | "configuration-policy-version-comparison"
  | "configuration-policy-future-window-preview"
    | "configuration-policy-employee-impact-preview"
    | "configuration-policy-restore-draft"
    | "configuration-policy-version-search"
    | "configuration-exception-policy-revision-read"
    | "configuration-exception-policy-revision-write"
    | "read-request-list"
    | "read-exception-queue"
    | "authorize-today-read"
    | "authorize-timesheet-read"
    | "authorize-request-decision"
    | "run-no-show-review"
    | "submit-self-request"
    | "decide-request"
    | "cancel-self-request"
    | "auth-workforce-capability"
    | "auth-workforce-schedule"
    | "auth-workforce-pilot-fence"
    | "auth-workforce-retention"
    | "auth-workforce-employment"
    | "auth-workforce-exception-queue"
    | "auth-workforce-exception-decision"
    | "attendance-devices-item-approve-post"
    | "attendance-devices-item-revoke-post"
    | "attendance-devices-get"
    | "attendance-security-triage-get"
    | "attendance-stations-item-disable-post"
    | "attendance-stations-item-qr-post"
    | "attendance-stations-item-replace-post"
    | "attendance-stations-get"
    | "attendance-stations-post"
    | "configuration-assignments-bulk-publish-post"
    | "configuration-assignments-preview-post"
    | "configuration-assignments-get"
    | "configuration-assignments-post"
    | "configuration-calendar-get"
    | "configuration-calendar-post"
    | "configuration-employment-events-get"
    | "configuration-employment-events-post"
    | "configuration-mobile-write-fence-cohorts-put"
    | "configuration-mobile-write-fence-cohorts-delete"
    | "configuration-mobile-write-fence-get"
    | "configuration-mobile-write-fence-put"
    | "configuration-policies-item-activate-post"
    | "configuration-policies-item-patch"
    | "configuration-policies-get"
    | "configuration-policies-post"
    | "configuration-shifts-item-activate-post"
    | "configuration-shifts-item-patch"
    | "configuration-shifts-default-get"
    | "configuration-shifts-default-post"
    | "configuration-shifts-get"
    | "configuration-shifts-post"
    | "configuration-shifts-team-default-get"
    | "configuration-shifts-team-default-post"
    | "configuration-site-assignments-bulk-publish-post"
    | "configuration-site-assignments-preview-post"
    | "configuration-site-assignments-get"
    | "configuration-site-assignments-post"
    | "configuration-sites-item-archive-post"
    | "configuration-sites-item-geofences-get"
    | "configuration-sites-item-geofences-post"
    | "configuration-sites-get"
    | "configuration-sites-post"
    | "exceptions-mine-get"
    | "timesheet-approvals-post"
    | "timesheet-get"
    | "today-get"
}): void {
  console.error("[workforce/privacy] sensitive operation failed", { operation: input.operation })
}

/** Optional enrichment failure: keep warning severity and discard private errors. */
export function logWorkforceSensitiveOperationWarning(input: {
  operation: "request-route-entitlement"
}): void {
  console.warn("[workforce/privacy] sensitive operation unavailable", { operation: input.operation })
}
