import json,pathlib,hashlib,re
r=pathlib.Path('/workspace/hrm-privacy-audit');paths=['docs/workforce-hrm-completion-roadmap-2026-08-30.md','docs/workforce-hrm-79-open-dependency-plan-2026-10-06.md','src/__tests__/api-mtm-mobile-sync-v2-stream-isolation.test.ts','src/__tests__/lib-mtm-mobile-sync-v2-rate-guard.test.ts','src/__tests__/api-mtm-mobile-sync-v2-workforce.test.ts','src/__tests__/api-mtm-mobile-sync-v2-routes.test.ts','src/__tests__/lib-mtm-mobile-sync-v2.test.ts','src/lib/mtm/mobile-sync-v2-rate-guard.ts','src/lib/public-abuse-guard.ts','src/app/api/v2/mtm/mobile/sync/routes/route.ts','src/app/api/v2/mtm/mobile/sync/workforce/route.ts','src/__tests__/api-mtm-mobile-bootstrap.test.ts','src/__tests__/workforce-h6-load-contract.test.ts']
bindings=[]
for p in paths:
 b=(r/p).read_bytes();bindings.append({'path':p,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()})
road=(r/paths[0]).read_text().splitlines();canonical={}
for i,line in enumerate(road,1):
 m=re.match(r'^\| (WF-C(?:12-004|12-005|13-006)) \|',line)
 if m:canonical[m[1]]={'line':i,'last_explicit_row':line}
scenarios=[
 {'id':'F1','criterion':'WF-C12-004','case':'Both directions: a pending dependency in one stream must not delay the other stream completion','method':'Controlled deferred promises with deterministic resolution, no real sleep. Assert healthy response before resolving failing dependency; no claim of SDK/network timeout enforcement.'},
 {'id':'F2','criterion':'WF-C12-004','case':'503 and429 bursts followed by recovery preserve independent Workforce/Route cursors','method':'Finite virtual sequence; assert each response stream, Retry-After bound, no cursor advance on failure and valid cursor only after successful page.'},
 {'id':'F3','criterion':'WF-C12-004','case':'An existing cursor reused for the other stream is rejected without reading its snapshot','method':'Real sealing/parser plus real handler and controlled database mocks, compare no foreign stream reads/writes.'},
 {'id':'F4','criterion':'WF-C12-005','case':'One noisy synthetic tenant or stream does not debit another tenant/stream budget','method':'Real rate guard into controlled local batch-counter adapter; all-or-nothing accounting. Explicitly no Redis-failover/productionfairness claim.'},
 {'id':'F5','criterion':'WF-C12-005','case':'Denied device/user/tenant bucket does not burn remaining buckets; initial-snapshot and pull budgets remain separate','method':'Exercise all three denial positions and retry-window boundaries under virtual clock; preserve existing thresholds.'},
 {'id':'F6','criterion':'WF-C12-005','case':'Oversized response recovers with smaller page and preserves cursor until success','method':'Actual serialization/page boundary; assert fixed413 recovery envelope, no payload in diagnostics and successful bounded retry.'},
 {'id':'F7','criterion':'WF-C12-005','case':'Poison operation disposition is terminal and metadata-only in current server/source contract','method':'Review/reuse existing terminal mappings; add only demonstrably missing contract cases. Physical Android encryptedqueue/processdeath proof remains external.'},
 {'id':'F8','criterion':'WF-C13-006','case':'Next dependency: Neither/HRM-only/Routes-only/Both failure matrix extends APIs to jobs/nav/sync','method':'Build per-surface gap table after F1-F7. Do not claim signedmobile or staging equivalence from bootstrap-only results.'},
]
plan={'status':'PREPARED_NOT_IMPLEMENTED_OR_EXECUTED','source_head':'8053702bbde2a43da537e263630f8a81ded2b659','next_slice':'WF-C12-004/005 bounded virtual fault and fairness matrix','canonical':canonical,'already_present_from_source_inspection':['Two API isolation scenarios: concurrent Workforceguard503 withRoute200; sequential Routedatabasefailure503 thenWorkforce200.','Rate guard already has three structural tests for exactdevice/user/tenant batch, atomicdenialpropagation andinitialsnapshotbudget.','Cursorlib covers tenant/agent/device/streambinding; routeAPIcovers429/503,leases,page/retention/scopechange.','WorkforceAPIcoversowncohort,entitlement,oversize413andcrossstreamcursor. Do not repeat acceptedcases without a missingcomposed boundary.'],'scenarios':scenarios,'proposed_new_paths':['src/__tests__/api-mtm-mobile-sync-v2-fault-fairness.test.ts','docs/workforce-c12-fault-fairness-matrix-2026-10-06.md'],'production_change_rule':'Only a reproduced owned correctness defect justifies a narrow source fix; no limit relaxation, featureactivation or sharedglobalpolicy rewrite. Freshscope/ownership review before firstwrite.','dependencies_not_required':['Historical api_keys creation baseline for synthetic local cases','Production telemetrycollector activation','Backup owner export completion'],'remaining_external_acceptance':['Real sustained overload/DBorRedisfailover with representative staging','Signed physical Android queue timing/processdeath/poisonquarantine','Approved5000usertrustoff/onload','Allfourentitlementmodes acrosssignedmobile/jobs/nav/API/failures'],'protected':['Support paths','Foreign MTM mock fixture','Baselines/denominator/canonicalstatuses','Migrationhistory/credentials/permissions','Productioncollector/deploy/merge/activation'],'exit_rule':'One finite composedmatrix with exactheadtests/review; record concrete remainingexternalgate. Do not cycle back through completed loggingcalls or markcanonicalDONEfromvirtualevidence.','source_bindings':bindings,'evidence_credit':'Preparation is source inspection only. Current2307PASS includesstreamisolation2tests; no newfault/fairnesscases have been executed.'}
pathlib.Path('/tmp/hrm-privacy-next-fault-fairness-plan.json').write_text(json.dumps(plan,indent=2)+'\n');print('prepared',len(scenarios),'finite scenarios;',len(bindings),'source bindings; no source edits')
