import { readFileSync } from "fs"
import path from "path"
import { describe, expect, it } from "vitest"

const source = (file: string) => readFileSync(path.join(process.cwd(), file), "utf8")

describe("complaint workspace UX contract", () => {
  it("keeps the registry compact, responsive, query-stable and explicit about failures", () => {
    const page = source("src/app/(dashboard)/complaints/page.tsx")
    expect(page).not.toMatch(/text-(?:3xl|4xl)/)
    expect(page).toContain("mobileCardRender")
    expect(page).toContain("router.replace(registryPath, { scroll: false })")
    expect(page).toContain("complaintScrollStorageKey")
    expect(page).toContain('document.querySelector<HTMLElement>("main")?.scrollTop')
    expect(page).toContain('scroller.scrollTo({ top: Number(saved) || 0')
    expect(page).not.toContain("String(window.scrollY)")
    expect(page).toContain("exportError")
    expect(page).toContain("fetchError")
    expect(page).toContain("hideResultCount")
    expect(page).toContain("document.title = localizedDocumentTitle")
    expect(page).toContain("currentRegistryPath !== registryPath")
    expect(page).toContain('data-testid="complaints-workspace"')
    expect(page).toContain('data-testid="complaints-empty-state"')
  })

  it("preserves create work and returns success to the same registry context", () => {
    const page = source("src/app/(dashboard)/complaints/new/page.tsx")
    expect(page).toContain("parseComplaintDraft")
    expect(page).toContain("serializeComplaintDraft")
    expect(page).toContain("beforeunload")
    expect(page).toContain("detailHref(json.data.id)")
    expect(page).toContain("sm:grid-cols-2")
    expect(page).toContain("const controller = new AbortController()")
    expect(page).toContain("window.setTimeout(async () =>")
    expect(page).toContain("signal: controller.signal")
    expect(page).toContain("if (!response.ok || !json?.success)")
    expect(page).toContain('data-testid="complaint-new-workspace"')
    expect(page).toContain('data-testid="complaint-new-form"')
  })

  it("keeps ownership, deadline, evidence and lifecycle actions in the detail workflow", () => {
    const page = source("src/app/(dashboard)/complaints/[id]/page.tsx")
    expect(page).toContain('t("caseOverview")')
    expect(page).toContain("data.slaDueAt")
    expect(page).toContain("changeAssignee")
    expect(page).toContain("comment.attachments?.map")
    expect(page).toContain("clientRequestId")
    expect(page).toContain("ConfirmDialog")
    expect(page).toContain('className="grid grid-cols-2 gap-x-3 gap-y-2')
    expect(page).toContain('data-testid="complaint-detail-workspace"')
  })

  it("shows mapping, row errors, partial retry and downloadable evidence during import", () => {
    const page = source("src/app/(dashboard)/complaints/import/page.tsx")
    const route = source("src/app/api/v1/complaints/import-xlsx/route.ts")
    expect(page).toContain("mappingPreview")
    expect(page).toContain("downloadErrors")
    expect(page).toContain("retryFailedRows")
    expect(page).toContain("md:hidden")
    expect(route).toContain("retryRows")
    expect(route).toContain("mapping")
    expect(route).toContain("MAX_FILE_SIZE")
    expect(page).toContain('data-testid="complaint-import-workspace"')
    expect(page).toContain('data-testid="complaint-import-dropzone"')
    expect(page).toContain('t("unknownMappingField")')
  })

  it("does not expose raw status or risk enum values", () => {
    const list = source("src/app/(dashboard)/complaints/page.tsx")
    const detail = source("src/app/(dashboard)/complaints/[id]/page.tsx")
    const importPage = source("src/app/(dashboard)/complaints/import/page.tsx")
    expect(list).toContain('t("unknownStatus")')
    expect(list).toContain('t("unknownRisk")')
    expect(detail).toContain('t("unknownStatus")')
    expect(detail).toContain('t("unknownRisk")')
    expect(list).toContain("sourceLabel(row.source)")
    expect(detail).toContain("sourceLabel(data.source)")
    expect(list).not.toContain('row.source || "—"')
    expect(detail).not.toContain('[t("fieldSource"), data.source]')
    for (const locale of ["en", "ru", "az"]) {
      const messages = JSON.parse(source(`messages/${locale}.json`))
      expect(messages.complaints.unknownSource, `${locale} complaints.unknownSource`).toBeTruthy()
    }
    expect(importPage).toContain('t("unknownStatus")')
    expect(importPage).toContain('t("unknownRisk")')
    expect(importPage).toContain("riskLabel(row.riskLevel)")
    expect(importPage).toContain("statusLabel(row.status)")
    expect(importPage).not.toContain('row.riskLevel || "—"')
    expect(importPage).not.toContain('row.status || "—"')
    expect(detail).toContain("priorityLabel(data.priority)")
    expect(detail).toContain('t("unknownPriority")')
    expect(detail).not.toContain('value={data.priority}')
    expect(list).not.toMatch(/: value\s*$/m)
    expect(detail).not.toMatch(/: (?:status|risk)\s*$/m)
  })

  it("enforces ticket permissions and tenant-scoped ownership across complaint routes", () => {
    const listRoute = source("src/app/api/v1/complaints/route.ts")
    const detailRoute = source("src/app/api/v1/complaints/[id]/route.ts")
    const importRoute = source("src/app/api/v1/complaints/import-xlsx/route.ts")
    const exportRoute = source("src/app/api/v1/complaints/export-xlsx/route.ts")
    expect(listRoute).toContain('withRlsAuth("tickets", "read"')
    expect(listRoute).toContain('withRlsAuth("tickets", "write"')
    expect(listRoute).toMatch(/assigneeIds[\s\S]*organizationId: orgId/)
    expect(detailRoute).toContain('withRlsAuth("tickets", "delete"')
    expect(detailRoute).toMatch(/auditUserIds[\s\S]*organizationId: orgId/)
    expect(detailRoute).toMatch(/d\.assignedTo[\s\S]*organizationId: orgId[\s\S]*Invalid assignee/)
    expect(importRoute).toContain('withRlsAuth("tickets", "write"')
    expect(importRoute).toContain("MAX_BASE64_LENGTH")
    expect(importRoute).toMatch(/payload\.base64\.length[\s\S]*File too large/)
    expect(importRoute).toMatch(/decoded\.byteLength[\s\S]*MAX_FILE_SIZE/)
    expect(exportRoute).toContain('withRlsAuth("tickets", "read"')
  })
})
