import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const flow = readFileSync("scripts/support-ux-service-desk-flow-evidence.mjs", "utf8")
const workflow = readFileSync(".github/workflows/support-ux-evidence.yml", "utf8")
const list = readFileSync("src/app/(dashboard)/tickets/page.tsx", "utf8")
const detail = readFileSync("src/app/(dashboard)/tickets/[id]/page.tsx", "utf8")
const report = readFileSync("src/components/tickets/ticketing-report.tsx", "utf8")
const aiSettings = readFileSync("src/app/(dashboard)/support/ai-settings/support-ai-settings-client.tsx", "utf8")
const dashboardLayout = readFileSync("src/app/(dashboard)/layout.tsx", "utf8")
const globals = readFileSync("src/app/globals.css", "utf8")

describe("Service Desk mutating flow evidence contract", () => {
  it("can run only against a disposable local evidence target", () => {
    expect(flow).toContain('SUPPORT_EVIDENCE_TARGET_MODE !== "ephemeral"')
    expect(flow).toContain('new Set(["127.0.0.1", "localhost", "::1"])')
    expect(flow).toContain("requireScreenshotTarget()")
    expect(flow).toContain("requireDemoTenant()")
    expect(flow).toContain("assertDemoTenant")
    expect(workflow).toContain("interaction_mode:")
    expect(workflow).toContain("SUPPORT_EVIDENCE_INTERACTION_MODE")
  })

  it("proves the reference queue interactions instead of declaring click counts", () => {
    for (const id of [
      "keyboard-open-and-return",
      "empty-queue-and-recovery",
      "stale-queue-and-recovery",
      "take-next-ticket",
      "internal-note-failure-and-recovery",
      "comment-permission-and-recovery",
      "composer-mode-navigation-and-draft-recovery",
      "closed-ticket-and-recovery",
      "support-ai-state-failure-and-recovery",
      "attachment-failure-and-recovery",
      "keyboard-case-controls-and-recovery",
      "support-ai-master-switch-boundary",
      "keyboard-reprioritize",
      "explicit-kanban-move",
      "kanban-move-failure-and-recovery",
      "filtered-no-results-and-reset",
      "reports-error-and-recovery",
      "loading-permission-and-recovery",
      "partial-context-failure-and-recovery",
      "stale-ticket-and-recovery",
    ]) {
      expect(flow).toContain(id)
    }
    expect(flow).toContain('page.keyboard.press("Enter")')
    expect(flow).toContain("tbody tr[tabindex='0']:visible, article[role='link']:visible")
    expect(flow).toContain('page.waitForEvent("filechooser"')
    expect(flow).toContain("keyboardFileChooser: true")
    expect(flow).toContain("keyboardModeSwitch: true")
    expect(flow).toContain("keyboardLeaveAction: true")
    expect(flow).toContain("queue_scroll_not_restored")
    expect(flow).toContain("queue_scroll_range_too_small")
    expect(flow).toContain('searchParams.get("focus") !== "mine"')
    expect(flow).toContain('searchParams.get("view") !== "list"')
    expect(flow).toContain('document.querySelector("main")?.scrollTop')
    expect(flow).toContain('candidate.request().method() === "POST"')
    expect(flow).toContain('candidate.request().method() === "PUT"')
    expect(flow).toContain("failed_send_did_not_preserve_draft")
    expect(flow).toContain("duplicate_send_not_blocked")
    expect(flow).toContain("duplicateSendBlocked: true")
    expect(flow).toContain('page.getByText(note, { exact: true }).waitFor')
    expect(flow).toContain('edit.press("Enter")')
    expect(flow).toContain("async function submitCaseControl")
    expect(flow).toContain('phase: "status_restore"')
    expect(flow).toContain('phase: "assignee_restore"')
    expect(flow).toContain('phase: "closed_ticket_close"')
    expect(flow).toContain("closed_ticket_reopen_http_")
    expect(flow).toContain('currentStatus?.value === "open" && statusSubmit?.dataset.state === "synced"')
    expect(flow).toContain("failed to restore ticket after closed-state evidence")
    expect(flow).toContain('page.getByRole("dialog").waitFor')
    expect(flow).toContain('"service-desk-flow-evidence.json"')
    expect(flow).toContain("report.results.length !== 20")
    expect(flow).toContain('page.getByTestId("tickets-loading")')
    expect(flow).toContain('page.getByTestId("ticket-context-error")')
    expect(flow).toContain('toggle.press("Enter")')
    expect(flow).toContain('page.getByTestId("ticket-detail-stale")')
    expect(flow).toContain("rollbackObserved: true")
    expect(flow).toContain("window.location.href")
    expect(flow).toContain('page.unrouteAll({ behavior: "ignoreErrors" })')
  })

  it("uses stable application-owned selectors for observable flow outcomes", () => {
    expect(list).toContain('data-testid="tickets-take-next"')
    expect(list).toContain("data-testid={`ticket-edit-${item.id}`}")
    expect(list).toContain("data-testid={`ticket-move-${ticket.id}`}")
    expect(detail).toContain('data-testid="ticket-detail-back"')
    expect(detail).toContain('data-testid="ticket-compose-internal"')
    expect(detail).toContain('data-testid="ticket-comment-composer"')
    expect(detail).toContain('data-testid="ticket-retry-send"')
    expect(list).toContain('data-testid="tickets-workspace"')
    expect(detail).toContain('data-testid="ticket-detail-workspace"')
    expect(list).toContain('data-testid="tickets-load-error"')
    expect(list).toContain('data-testid="tickets-refresh"')
    expect(list).toContain('data-testid="tickets-filter-scroller"')
    expect(list).toContain('data-testid="tickets-search"')
    expect(list).toContain('data-testid="tickets-kanban-viewport"')
    expect(list).toContain('data-testid={tickets.length === 0 ? "tickets-empty-state"')
    expect(list).toContain('"tickets-no-results-state"')
    expect(detail).toContain('data-testid="ticket-context-retry"')
    expect(detail).toContain('data-testid="ticket-secondary-context"')
    expect(detail).toContain('data-testid="ticket-secondary-context-toggle"')
    expect(detail).toContain('data-testid="ticket-detail-retry-stale"')
    expect(detail).toContain('data-testid="ticket-attachment-input"')
    expect(detail).toContain('data-testid="ticket-attachment-error"')
    expect(detail).toContain('data-testid="ticket-retry-attachment"')
    expect(detail).toContain('data-testid="ticket-status-select"')
    expect(detail).toContain('<option value="open">{t("statusOpen")}</option>')
    expect(detail).toContain('data-testid="ticket-status-submit"')
    expect(detail).toContain('data-state={updatingStatus ? "saving"')
    expect(detail).toContain('data-testid="ticket-assignee-select"')
    expect(detail).toContain('data-testid="ticket-assignee-submit"')
    expect(detail).toContain('data-state={updatingAssignee ? "saving"')
    expect(detail).toContain('data-testid="ticket-ai-state"')
    expect(detail).toContain('data-testid="ticket-ai-retry-state"')
    expect(detail).toContain('supportAiStateError ? "unavailable" : !supportAiHasLoaded ? "loading"')
    expect(detail).toContain('data-testid="ticket-closed-state"')
    expect(detail).toContain('data-testid="ticket-reopen"')
    expect(detail).toContain('data-testid="ticket-escalate"')
    expect(detail).toContain('status: "open", closedAt: null, resolvedAt: null')
    expect(detail).toContain('fetch(`/api/v1/tickets/${ticketId}`, { cache: "no-store" })')
    expect(detail).toContain('void fetchTicket({ silent: true })')
    expect(aiSettings).toContain('data-testid="support-ai-settings-workspace"')
    expect(aiSettings).toContain('data-testid="support-ai-master-switch"')
    expect(aiSettings).toContain('data-testid="support-ai-confirm-disable"')
    expect(report).toContain('data-testid="ticketing-report-loading"')
    expect(report).toContain('"ticketing-report-error"')
    expect(report).toContain('data-testid="ticketing-report-retry"')
    expect(report).toContain('{t("retry")}')
    expect(report).not.toContain('tc("retry")')
    expect(report).toContain('data-testid="ticketing-report-workspace"')
    expect(report).toContain('data-testid="ticketing-report-advanced-filters"')
    expect(report).toContain('data-testid="ticketing-report-secondary-metrics"')
    expect(report).toContain('className="grid min-w-0 gap-5 lg:grid-cols-3"')
    expect(report.match(/<section className="min-w-0 space-y-/g)).toHaveLength(3)
    expect(report).toContain("grid-cols-[minmax(0,1fr)_42px_50px_56px]")
    expect(report).toContain('className="flex flex-col items-start gap-2 sm:flex-row sm:justify-between"')
    expect(report).toContain("const primaryMetrics = metrics.slice(0, 4)")
    expect(report).toContain("const secondaryMetrics = metrics.slice(4)")
    expect(report).toContain('<Button type="submit" size="sm">')
    expect(report).not.toContain('className="bg-orange-700 text-white hover:bg-orange-800 hover:text-white"')
    expect(report).toContain('tone: "text-red-700 dark:text-red-300"')
    expect(report).not.toContain('tone: "text-destructive"')
    expect(report.match(/inline-flex min-h-11 items-center/g)).toHaveLength(2)
    expect(report).toContain("if (!res.ok || !json.success || !json.data?.serviceDesk)")
    expect(flow).toContain('aiBody?.errorKey !== "supportAiDisabled"')
    expect(flow).toContain('data: { feature: "supportAiDisabled", action: "remove" }')
    expect(flow).toContain('page.getByTestId("ticket-form-priority")')
    expect(flow).toContain('viewportName === "mobile"')
    expect(flow).toContain('page.getByTestId("ticket-escalate")')
    expect(flow).toContain("visibleMobileControl: true")
    expect(flow).toContain("failed to restore ticket priority after mobile evidence")
    expect(flow).toContain("const relocatedMove = page.getByTestId(moveTestId)")
    expect(flow).toContain("async function dismissTour")
    expect(flow).toContain("support_ai_disable_not_persisted")
    expect(flow).toContain("support_ai_agent_state_not_disabled")
    expect(flow).toContain("support_ai_cross_tenant_evidence_session")
    expect(flow).toContain("authenticatedOrganizationId")
    expect(flow).toContain('requiredEnv("SUPPORT_EVIDENCE_ORGANIZATION_ID")')
    expect(flow).toContain("context.request.get(`/api/v1/tickets/${referenceTicketId}`)")
    expect(flow).toContain("body?.data?.id !== referenceTicketId")
    expect(flow).toContain("body?.data?.subject?.includes(demoOrganization)")
    expect(flow).toContain('organizationSlug: demoOrganizationSlug')
    expect(flow).toContain('json: "true"')
    expect(flow).toContain('context.cookies(baseUrl)')
    expect(flow.indexOf("await authenticate(context)"))
      .toBeLessThan(flow.indexOf("page = await context.newPage()"))
    expect(workflow).toContain("LEADDRIVE_RUNTIME_DIR: ${{ runner.temp }}/leaddrive-support-ux-runtime-")
    expect(workflow).toContain("LEADDRIVE_LOG_DIR: ${{ runner.temp }}/leaddrive-support-ux-logs-")
    expect(workflow).toContain("SUPPORT_EVIDENCE_ORGANIZATION_ID")
    expect(workflow).toContain(".organization.id // empty")
    expect(workflow).toContain("SCREENSHOT_BASE_URL: ${{ inputs.target_mode == 'ephemeral' && 'http://localhost:3000'")
    expect(workflow).toContain("NEXTAUTH_URL: http://localhost:3000")
    expect(workflow.lastIndexOf("node scripts/support-ux-service-desk-flow-evidence.mjs"))
      .toBeLessThan(workflow.lastIndexOf("node scripts/support-ux-browser-evidence.mjs"))
  })

  it("keeps the case controls named, localized and touch-operable", () => {
    expect(detail).toContain('aria-label={tc("subject")}')
    expect(detail).toContain('aria-label={tc("description")}')
    expect(detail).toContain('aria-label={tc("status")}')
    expect(detail).toContain('aria-label={tc("assigned")}')
    expect(detail).toContain('aria-label={t("entitlementWaiveReason")}')
    expect(detail).toContain("categoryLabel(ticket.category)")
    expect(detail).not.toContain("CATEGORY_LABELS[ticket.category] || ticket.category")
    expect(detail).toContain("h-11 w-48 sm:h-9")
  })

  it("keeps status and exception filters in one compact toolbar", () => {
    expect(list).toContain('data-testid="tickets-escalated-filter"')
    expect(list).not.toContain('aria-label={t("statusFilters")}')
    expect(list).toContain('aria-label={t("workspaceFilters")}')
    expect(list).toContain("grid grid-cols-3 gap-1")
    expect(list).toContain("flex gap-2 overflow-x-auto")
    expect(list).toContain("sm:grid-cols-[repeat(3,minmax(0,1fr))_auto_auto]")
    expect(list).toContain("[contain:inline-size]")
    expect(list).toContain("md:sticky md:top-2")
    expect(list).not.toContain("sticky top-2 z-20")
    expect(list).toContain('className="order-first flex h-11 min-w-32')
    expect(list).toContain('view === key ? "ml-1 whitespace-nowrap sm:sr-only" : "sr-only"')
  })

  it("keeps Russian dashboard copy in the intentional sans-serif system", () => {
    expect(dashboardLayout).toContain('variable: "--font-dashboard"')
    expect(dashboardLayout).toContain("font-dashboard relative")
    expect(dashboardLayout).not.toContain("jakarta.className")
    expect(globals).toContain("font-family: var(--font-dashboard), ui-sans-serif, system-ui")
    expect(globals).toContain('BlinkMacSystemFont, "Segoe UI", sans-serif;')
  })

  it("contains the Kanban lane scroller inside the workspace width", () => {
    expect(list).toContain('data-testid="tickets-kanban-viewport" className="w-full min-w-0 max-w-full overflow-x-auto overscroll-x-contain pb-4 [contain:inline-size]"')
    expect(list).toContain('className="flex w-max min-w-full items-start gap-3"')
  })

  it("uses readable SLA text tones in light and dark ticket surfaces", () => {
    expect(list).toContain('warning: "text-amber-700 dark:text-amber-300"')
    expect(list).toContain('ok: "text-green-700 dark:text-green-300"')
    expect(list).toContain('breached: "text-red-700 dark:text-red-300"')
    expect(list).not.toContain('warning: "text-amber-500"')
    expect(list).not.toContain('ok: "text-green-600 dark:text-green-400"')
  })
})
