import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

function source(path: string): string {
  return readFileSync(path, "utf8")
}

function scenarioSource(runner: string, id: string): string {
  const marker = `id: "${id}"`
  const markerIndex = runner.indexOf(marker)
  if (markerIndex < 0) return ""
  const start = runner.lastIndexOf("\n  {", markerIndex)
  const next = runner.indexOf("\n  {\n    id: ", markerIndex + marker.length)
  return runner.slice(start, next < 0 ? runner.length : next)
}

describe("SwissMed MTM browser evidence runner", () => {
  const runner = source("scripts/swissmed-mtm-browser-evidence.mjs")
  const helpers = source("scripts/swissmed-mtm-evidence-helpers.mjs")
  const workflow = source(".github/workflows/swissmed-mtm-browser-evidence.yml")

  it("keeps exactly one labelled scenario for every SWM reference", () => {
    const ids = [...runner.matchAll(/id: "(SWM-\d{2})"/g)].map((match) => match[1])
    expect(ids).toHaveLength(18)
    expect(new Set(ids)).toEqual(new Set(
      Array.from({ length: 18 }, (_, index) => "SWM-" + String(index + 1).padStart(2, "0")),
    ))
  })

  it("is read-only after the credentials callback", () => {
    expect(runner).toContain('context.request.post("/api/auth/callback/credentials"')
    expect(runner).not.toContain("page.request.post(")
    expect(runner).not.toContain("page.request.put(")
    expect(runner).not.toContain("page.request.patch(")
    expect(runner).not.toContain("page.request.delete(")
    expect(runner).not.toContain('page.getByText("Save")')
  })

  it("captures role, viewport, overflow, errors and screenshots", () => {
    expect(runner).toContain('key: "admin"')
    expect(runner).toContain('key: "agent"')
    expect(runner).toContain("desktop: { width: 1440, height: 1000 }")
    expect(runner).toContain("tablet: { width: 1024, height: 1366 }")
    expect(runner).toContain('"tablet-landscape": { width: 1180, height: 820 }')
    expect(runner).toContain("phone: { width: 390, height: 844 }")
    expect(runner).toContain("horizontalOverflow")
    expect(runner).toContain("consoleErrors")
    expect(runner).toContain("pageErrors")
    expect(runner).toContain("responseErrors")
    expect(runner).toContain("telemetryResponseErrors")
    expect(runner).toContain("telemetryConsoleErrors")
    expect(runner).toContain("report.totals = {")
    expect(runner).toContain('result.status === "blocked"')
    expect(runner).toContain('result.status === "failed"')
    expect(runner).toContain("externalConsoleErrors")
    expect(runner).toContain("responseUrl.origin !== baseOrigin")
    expect(helpers).toContain("source.origin !== baseOrigin")
    expect(runner).toContain("page.screenshot")
    expect(runner).toContain('status: consoleErrors.length || externalConsoleErrors.length || pageErrors.length || responseErrors.length || horizontalOverflow ? "failed" : "passed"')
  })

  it("fails tablet evidence when responsive controls are clipped or covered", () => {
    expect(runner).toContain('const tabletViewportNames = new Set(["tablet", "tablet-landscape"])')
    expect(runner).toContain("async function assertTabletScenarioGeometry(page, scenarioId, viewportName)")
    expect(runner).toContain("if (tabletViewportNames.has(viewportName))")
    expect(runner).toContain("await assertTabletScenarioGeometry(page, scenario.id, viewportName)")
    expect(runner.indexOf("await assertTabletScenarioGeometry(page, scenario.id, viewportName)"))
      .toBeGreaterThan(runner.indexOf("if (scenario.prepare) await scenario.prepare(page, resources, viewportName)"))

    expect(runner).toContain('testId("global-header")')
    expect(runner).toContain('document.querySelector(\'[data-tour-id="app-launcher"]\')')
    expect(runner).toContain('testId("global-header-actions")')
    expect(runner).toContain("global_header_launcher_actions_overlap")

    expect(runner).toContain('testId("mtm-location-history-filter-form")')
    expect(runner).toContain('testId("mtm-location-history-accuracy")')
    expect(runner).toContain('testId("mtm-location-history-submit")')
    expect(runner).toContain("location_history_filter_form_overflow")

    expect(runner).toContain('testId("mtm-route-view-switcher")')
    expect(runner).toContain("route_switcher_tabs_hidden")
    expect(runner).toContain('testId("mtm-route-builder-actions")')
    expect(runner).toContain("route_builder_actions_overlay_risk")
    expect(runner).toContain("route_builder_actions_overlap_content")

    expect(runner).toContain('testId("mtm-matrix-agent-select")')
    expect(runner).toContain('testId("mtm-week-day-list")')
    expect(runner).toContain("weekly_day_list_missing")
    expect(runner).toContain("weekly_day_list_clipped")

    expect(runner).toContain('testId("mtm-kpi-applied-scope")')
    expect(runner).toContain("kpi_applied_scope_text_clipped")
    expect(runner).toContain('document.querySelector("#mtm-kpi-filters")')
    expect(runner).toContain("kpi_filters_overflow")

    expect(runner).toContain('currentScenarioId === "SWM-09" && currentViewportName === "tablet-landscape"')
    expect(runner).toContain('currentScenarioId === "SWM-09" && currentViewportName === "tablet"')
    expect(runner).toContain('testId("mtm-pharmacy-tablet-master-detail")')
    expect(runner).toContain('testId("mtm-pharmacy-tablet-inspector")')
    expect(runner).toContain('testId("mtm-pharmacy-column-chooser")')
    expect(runner).toContain('testId("mtm-pharmacy-filter-sheet")')
    expect(runner).toContain('testId("mtm-pharmacy-filter-reset")')
    expect(runner).toContain('testId("mtm-pharmacy-filter-apply")')
    expect(runner).toContain("pharmacy_tablet_master_inspector_overlap")
    expect(runner).toContain("pharmacy_column_chooser_touch_target_small")
    expect(runner).toContain("pharmacy_column_chooser_overlaps_workspace")
    expect(runner).toContain("pharmacy_filter_sheet_not_full_height")
    expect(runner).toContain("pharmacy_filter_${code}_touch_target_small")
  })

  it("classifies only the exact CSP telemetry POST endpoint as non-blocking", () => {
    expect(runner).toContain('method === "POST" && url === "/api/v1/public/csp-report"')
    expect(runner).not.toContain('status === 429 && method === "POST"')
    expect(runner).toContain("isNonBlockingTelemetryResponse(responseError)")
    expect(runner).toContain("telemetryResponseErrors.push(responseError)")
    expect(runner).toContain("responseErrors.push(responseError)")
  })

  it("keeps external console noise diagnostic while first-party and unknown errors remain blocking", () => {
    expect(helpers).toContain('if (!url) return "blocking"')
    expect(helpers).toContain('source.protocol === "http:" || source.protocol === "https:"')
    expect(runner).toContain('bucket === "external"')
    expect(runner.match(/externalConsoleErrors,/g)).toHaveLength(2)
    const passFailLine = runner.split("\n").find((line) => line.includes('horizontalOverflow ? "failed" : "passed"')) ?? ""
    expect(passFailLine).toContain("externalConsoleErrors")
  })

  it("records CSP report delivery errors without failing an otherwise healthy screen", () => {
    expect(helpers).toContain("telemetryRequestUrls.has(source.href)")
    expect(helpers).toContain('return "telemetry"')
    expect(runner).toContain('page.on("request"')
    expect(runner).toContain("telemetryRequestUrls.add(requestUrl.href)")
    expect(runner).toContain("consoleErrorBucket(entry.url, baseURL, baseOrigin, telemetryRequestUrls)")
    expect(runner).toContain('bucket === "telemetry"')
    expect(runner).toContain("telemetryConsoleErrors.push(entry)")
    const passFailLine = runner.split("\n").find((line) => line.includes('horizontalOverflow ? "failed" : "passed"')) ?? ""
    expect(passFailLine).not.toContain("telemetryConsoleErrors")
  })

  it("locks secret-managed principals to the current production acceptance tenant", () => {
    expect(workflow).toContain("workflow_dispatch:")
    expect(workflow).toContain("environment: production")
    expect(workflow).toContain("https://app.leaddrivecrm.org")
    expect(workflow).toContain("default: leaddrive")
    expect(workflow).toContain('MTM_EVIDENCE_BASE_URL" != "https://app.leaddrivecrm.org')
    expect(workflow).toContain('MTM_EVIDENCE_ORG_SLUG" != "leaddrive')
    expect(workflow).toContain("qa.swissmed.admin@leaddrivecrm.org")
    expect(workflow).toContain("qa.swissmed.agent@leaddrivecrm.org")
    expect(workflow).toContain("secrets.MTM_EVIDENCE_ADMIN_EMAIL")
    expect(workflow).toContain("secrets.MTM_EVIDENCE_AGENT_EMAIL")
    expect(workflow).toContain("if: always()")
    expect(workflow).toContain("retention-days: 30")
  })

  it("bounds each production run to one role, one viewport and at most nine scenarios", () => {
    expect(workflow).toContain("default: admin")
    expect(workflow).not.toContain("- admin,agent")
    expect(workflow).toContain("default: desktop")
    expect(workflow).toContain("- tablet-landscape")
    expect(workflow).toContain("desktop|tablet|tablet-landscape|phone")
    expect(workflow).not.toContain("- desktop,tablet,phone")
    expect(workflow).toContain("scenario_batch:")
    expect(workflow).toContain("default: planning")
    expect(workflow).toContain('case "$MTM_EVIDENCE_ROLES" in')
    expect(workflow).toContain('case "$MTM_EVIDENCE_VIEWPORTS" in')
    expect(workflow).toContain('case "$MTM_EVIDENCE_SCENARIO_BATCH" in')
    expect(runner).toContain("isProductionEvidenceTarget(baseURL)")
    expect(runner).toContain('throw new Error("mtm_evidence_production_requires_one_role")')
    expect(runner).toContain('throw new Error("mtm_evidence_production_requires_one_viewport")')
    expect(runner).toContain('selectedScenarioIds.size > 9')
    expect(runner).toContain('if (selectedScenarioIds && !selectedScenarioIds.has(scenario.id)) continue')

    const batchSource = runner.slice(
      runner.indexOf("const scenarioBatches"),
      runner.indexOf("const roles"),
    )
    const batchedIds = [...batchSource.matchAll(/"(SWM-\d{2})"/g)].map((match) => match[1])
    expect(batchedIds).toHaveLength(18)
    expect(new Set(batchedIds)).toEqual(new Set(
      Array.from({ length: 18 }, (_, index) => "SWM-" + String(index + 1).padStart(2, "0")),
    ))
  })

  it("refreshes only explicitly confirmed deployed fixtures over pinned SSH", () => {
    expect(workflow).toContain("refresh_fixtures:")
    expect(workflow).toContain("default: false")
    expect(workflow).toContain('MTM_EVIDENCE_FIXTURE_CONFIRMATION" != "leaddrive-swissmed-evidence')
    expect(workflow).toContain("SERVER_SSH_KNOWN_HOSTS")
    expect(workflow).toContain("ssh-keygen -F")
    expect(workflow).not.toContain("ssh-keyscan")
    expect(workflow).toContain("EXPECTED_SEED_SHA")
    expect(workflow).toContain("actual_seed_sha")
    expect(workflow).toContain("deployed seed does not match the reviewed workflow revision")
    expect(workflow).toContain("MTM_EVIDENCE_PASSWORD=\"$password\"")
    expect(workflow).toContain('APP_ENV_FILE="${APP_ENV_FILE:-/etc/leaddrive/app.env}"')
    expect(workflow).toContain('node --env-file="$APP_ENV_FILE" "$SEED"')
    expect(workflow).not.toContain('. "$APP_ENV_FILE"')
    expect(workflow).not.toContain("scp scripts/seeds")
  })

  it("uses stable non-visual hooks for interactive route states", () => {
    expect(source("src/app/(dashboard)/mtm/routes/page.tsx")).toContain('data-testid="mtm-routes-view-matrix"')
    expect(source("src/app/(dashboard)/mtm/routes/page.tsx")).toContain('data-testid="mtm-routes-more-views"')
    expect(source("src/app/(dashboard)/mtm/routes/page.tsx")).toContain('data-testid="mtm-routes-more-views-toggle"')
    expect(runner).toContain('page.getByTestId("mtm-routes-more-views-toggle").click()')
    expect(source("src/app/(dashboard)/mtm/routes/page.tsx")).toContain('data-testid="mtm-route-builder-open"')
    expect(source("src/components/mtm/route-planning-matrix.tsx")).toContain('data-testid="mtm-route-planning-matrix"')
    expect(source("src/components/mtm/route-planning-matrix.tsx")).toContain('data-testid="mtm-matrix-agent-select"')
    expect(source("src/components/mtm/route-planning-matrix.tsx")).toContain('data-testid="mtm-matrix-candidate"')
    expect(source("src/components/mtm/route-planning-matrix.tsx")).toContain('data-testid="mtm-week-day-list"')
    expect(source("src/components/mtm/route-builder.tsx")).toContain('data-testid="mtm-route-builder"')
    expect(source("src/components/mtm/route-builder.tsx")).toContain('data-testid="mtm-route-candidate"')
    expect(source("src/components/mtm/route-builder.tsx")).toContain('data-testid="mtm-route-builder-actions"')
    expect(source("src/components/mtm/organization-explorer.tsx")).toContain('data-testid="mtm-organization-grid-settings"')
    expect(source("src/components/mtm/organization-explorer.tsx")).toContain('data-testid={`mtm-organization-density-${value.toLowerCase()}`}')
    expect(source("src/components/mtm/organization-explorer.tsx")).toContain('data-testid="mtm-organization-grid-scroll"')
    expect(source("src/components/mtm/operational-week-home.tsx")).toContain('data-testid="mtm-operational-week"')
    expect(source("src/components/mtm/operational-week-home.tsx")).toContain('data-testid={`mtm-swm15-coverage-${railId}`}')
    expect(source("src/components/mtm/contact-detail.tsx")).toContain('data-testid="mtm-contact-scoring-state"')
    expect(source("src/components/mtm/contact-explorer.tsx")).toContain('data-testid="mtm-contact-transfer-open"')
    expect(source("src/components/mtm/contact-transfer-dialog.tsx")).toContain('data-testid="mtm-contact-transfer-dialog"')
    expect(source("src/components/mtm/location-history-panel.tsx")).toContain('data-testid="mtm-location-history-results"')
    expect(source("src/components/mtm/location-history-panel.tsx")).toContain('data-testid="mtm-location-history-replay"')
    expect(source("src/components/mtm/location-history-panel.tsx")).toContain('data-testid="mtm-location-history-filter-form"')
    expect(source("src/components/mtm/location-history-panel.tsx")).toContain('data-testid="mtm-location-history-accuracy"')
    expect(source("src/components/mtm/location-history-panel.tsx")).toContain('data-testid="mtm-location-history-submit"')
    expect(source("src/components/mtm/task-workspace.tsx")).toContain('data-testid="mtm-task-recurrence"')
    expect(source("src/components/mtm/explainable-kpi-dashboard.tsx")).toContain('data-testid="mtm-explainable-kpi"')
    expect(source("src/components/mtm/explainable-kpi-dashboard.tsx")).toContain('data-testid="mtm-kpi-applied-scope"')
    expect(source("src/components/mtm/organization-explorer.tsx")).toContain('data-testid="mtm-organization-explorer"')
    expect(source("src/components/mtm/organization-detail.tsx")).toContain('data-testid="mtm-organization-detail"')
    expect(source("src/components/mtm/contact-explorer.tsx")).toContain('data-testid="mtm-contact-explorer"')
    expect(source("src/components/mtm/contact-detail.tsx")).toContain('data-testid="mtm-contact-detail"')
    expect(source("src/components/mtm/pharmacy-promotion-workspace.tsx")).toContain('data-testid="mtm-pharmacy-promotions"')
    expect(source("src/components/mtm/live-map.tsx")).toContain('data-testid="mtm-live-map-canvas"')
    expect(source("src/components/header.tsx")).toContain('data-testid="global-header"')
    expect(source("src/components/header.tsx")).toContain('data-testid="global-header-actions"')
  })

  it("requires every scenario to prove its target UI before passing", () => {
    expect(runner).toContain("if (!scenario.waitFor && !scenario.prepare)")
    expect(runner).toContain('throw new Error("mtm_evidence_target_assertion_missing_" + scenario.id)')
    expect(runner).toContain("[data-testid=mtm-task-workspace] [data-testid=mtm-task-recurrence]")
    expect(runner).toContain("[data-testid=mtm-explainable-kpi][data-state=ready]")
    expect(runner).toContain("[data-testid=mtm-organization-explorer][data-effective-scope=MINE][aria-busy=false]")
    expect(runner).toContain("[data-testid=mtm-pharmacy-promotions][aria-busy=false]")
    expect(runner).toContain("[data-testid=mtm-live-map-canvas][data-ready=true] .leaflet-container")
    expect(runner).toContain("[data-testid=mtm-organization-detail]")
    expect(runner).toContain("[data-testid=mtm-contact-explorer][aria-busy=false]")
    expect(runner).toContain("[data-testid=mtm-contact-detail]")
  })

  it("blocks SWM-09 until the exact QA promotion execution is visible", () => {
    const scenario = scenarioSource(runner, "SWM-09")
    expect(scenario).toContain("path: (resources) => resources.promotionReviewExecutionId")
    expect(scenario).toContain('fallbackPath: "/mtm/promotions"')
    expect(scenario).toContain('"qa_reviewable_pharmacy_promotion_missing"')
    expect(scenario).toContain('data-testid="mtm-pharmacy-review-${resources.promotionReviewExecutionId}"')
    expect(scenario).toContain('getByTestId("mtm-pharmacy-review-dialog")')
    expect(scenario).toContain('viewportName === "tablet-landscape"')
    expect(scenario).toContain('getByTestId("mtm-pharmacy-tablet-master-detail")')
    expect(scenario).toContain('getByTestId("mtm-pharmacy-tablet-inspector")')
    expect(scenario).toContain('getByTestId("mtm-pharmacy-column-chooser")')
    expect(scenario).toContain('mtm-pharmacy-tablet-row-${resources.promotionReviewExecutionId}')
    expect(scenario).toContain('data-execution-id="${resources.promotionReviewExecutionId}"')
    expect(scenario).toContain('getByTestId("mtm-pharmacy-column-source")')
    expect(scenario).toContain('data-source-visible="false"')
    expect(scenario).toContain('page.reload({ waitUntil: "domcontentloaded" })')
    expect(scenario).toContain('getByTestId("mtm-pharmacy-filter-reset")')
    expect(scenario).toContain('getByTestId("mtm-pharmacy-filter-apply")')
    expect(scenario).not.toContain("path: () =>")
    const agentScenarioBlock = runner.slice(runner.indexOf("const agentScenarios"), runner.indexOf("const scenarios"))
    expect(agentScenarioBlock).not.toContain('"SWM-09"')
  })

  it("blocks SWM-12 until the exact QA agent has a rendered live coordinate", () => {
    const scenario = scenarioSource(runner, "SWM-12")
    expect(scenario).toContain("path: (resources) => resources.liveAgentId")
    expect(scenario).toContain('fallbackPath: "/mtm/map"')
    expect(scenario).toContain('"qa_live_agent_coordinate_missing"')
    expect(scenario).toContain('getByTestId("mtm-map-employee-filter").fill("[QA-SWISSMED] Field Agent")')
    expect(scenario).toContain('getAttribute("data-rendered-agent-ids")')
    expect(scenario).not.toContain("path: () =>")
    expect(runner).toContain('typeof scenario.missingReason === "function"')
  })

  it("pins scenario evidence to the dedicated QA field fixtures", () => {
    expect(runner).toContain('/mtm?weekAgentId=${encodeURIComponent(resources.agentId)}')
    expect(runner).toContain("/api/v1/mtm/organizations?search=QA-SWM-CLINIC&limit=1")
    expect(runner).toContain("/api/v1/mtm/tasks?search=QA-SWISSMED&limit=1")
    expect(runner).toContain('includes("[QA-SWISSMED] Field Agent")')
    expect(runner).toContain("qa_reviewable_pharmacy_promotion_missing")
    expect(runner).toContain("qa_live_agent_coordinate_missing")
    expect(runner).toContain("findQaPromotionReviewExecutionId(promotionPayload, agentId)")
    expect(helpers).toContain('candidate?.target?.customerCode === "QA-SWM-PHARMACY"')
    expect(helpers).toContain('candidate?.policy?.ready === true')
    expect(runner).toContain("findQaLiveAgentId(livePayload, agentId)")
    expect(runner).toContain('getByTestId("mtm-matrix-agent-select").selectOption(resources.agentId)')
    expect(runner).toContain('locator("#route-builder-primary").selectOption(resources.agentId)')
    expect(runner).toContain('getByTestId("mtm-organization-density-compact").click()')
    expect(runner).toContain('data-column="lastVisit"')
    expect(runner).toContain('getByTestId("mtm-organization-assign-open").click()')
    expect(runner).toContain('getByTestId("mtm-organization-assignment-dialog")')
    expect(runner).toContain('data-loaded-agent-id="${resources.agentId}"')
    expect(runner).toContain('swm08_last_visit_column_obscured')
    expect(runner).toContain("await scenario.prepare(page, resources, viewportName)")
    expect(runner).toContain("todayDate")
    expect(source("src/components/mtm/pharmacy-promotion-workspace.tsx")).toContain('data-testid={`mtm-pharmacy-promotion-${row.id}`}')
    expect(source("src/components/mtm/live-map.tsx")).toContain('data-rendered-agent-ids={renderedAgentIds.join(",")}')
    expect(source("src/app/(dashboard)/mtm/map/page.tsx")).toContain('data-testid="mtm-map-employee-filter"')
  })
})
