import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"

const androidRoot = resolve(process.cwd(), "apps/workforce-android")
const read = (path: string) => readFileSync(resolve(androidRoot, path), "utf8")

describe("Workforce Android foundation", () => {
  it("keeps the source project Android-first and refuses an implicit production release identity", () => {
    const build = read("app/build.gradle.kts")
    expect(build).toContain("id(\"com.android.application\")")
    expect(build).toContain("id(\"org.jetbrains.kotlin.plugin.compose\")")
    expect(build).toContain("compileSdk = 37")
    expect(build).toContain("WORKFORCE_APPLICATION_ID")
    expect(build).toContain("invalid.release.workforce")
    expect(build).toContain("WORKFORCE_API_BASE_URL")
    expect(build).not.toMatch(/applicationId\s*=\s*\"com\.leaddrive\.workforce\"/)
  })

  it("does not declare background location or backup of employee session data", () => {
    const manifest = read("app/src/main/AndroidManifest.xml")
    const dataRules = read("app/src/main/res/xml/data_extraction_rules.xml")
    expect(manifest).toContain("ACCESS_FINE_LOCATION")
    expect(manifest).toContain("barcode_ui")
    expect(manifest).toContain("android.permission.USE_BIOMETRIC")
    expect(manifest).toContain("android.permission.POST_NOTIFICATIONS")
    expect(manifest).not.toContain("android.permission.CAMERA")
    expect(manifest).not.toContain("ACCESS_BACKGROUND_LOCATION")
    expect(manifest).not.toContain("foregroundServiceType=\"location\"")
    expect(manifest).toContain("android:allowBackup=\"false\"")
    expect(dataRules).toContain("<exclude domain=\"sharedpref\" path=\".\" />")
    expect(dataRules).toContain("<exclude domain=\"database\" path=\".\" />")
  })

  it("keeps the Android data layer limited to Workforce login, server-truth work time and secure local session state", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const store = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSecureStore.kt")
    expect(api).toContain('"/api/v1/mtm/mobile/auth"')
    expect(api).toContain('"/api/v1/mtm/mobile/bootstrap"')
    expect(api).toContain('"/api/v1/mtm/mobile/workday"')
    expect(api).toContain('"/api/v1/mtm/mobile/sync/push"')
    expect(api).toContain('override val entity = "workdays"')
    expect(api).toContain('"schemaVersion", WORKFORCE_WORKDAY_SCHEMA_VERSION')
    expect(api).toContain("UUID.randomUUID()")
    expect(api).toContain("if (activeWorkday == null)")
    expect(api).not.toContain('"/api/v1/mtm/mobile/routes')
    expect(api).not.toContain('"/api/v1/mtm/mobile/visits')
    expect(api).toContain('"x-workforce-client"')
    expect(api).toContain('"x-workforce-app-version-code"')
    expect(store).toContain("AndroidKeyStore")
    expect(store).toContain("AES/GCM/NoPadding")
    expect(store).toContain("clearForLogout")
  })

  it("restores canonical Today state after process death and never manufactures an offline fact", () => {
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    expect(activity).toContain("LaunchedEffect(Unit)")
    expect(activity).toContain("repository.restore()")
    expect(activity).toContain("repository.loadToday()")
    expect(activity).toContain("R.string.worktime_unavailable")
    expect(activity).toContain("val updateRequiredBeforeChanges = stringResource")
    expect(activity).not.toContain("context.getString(R.string.update_required_before_changes)")
    expect(activity).toContain("R.string.today_outbox_disclaimer")
    expect(repository).toContain("submitTodayAction")
  })

  it("renders only server-selected immutable schedule context and never treats it as a presence proof", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const defaultStrings = read("app/src/main/res/values/strings.xml")
    const russianStrings = read("app/src/main/res/values-ru/strings.xml")
    const azerbaijaniStrings = read("app/src/main/res/values-az/strings.xml")
    expect(api).toContain("toWorkdayScheduleSegment")
    expect(api).toContain('state !in setOf("CURRENT", "NEXT")')
    expect(api).toContain("WORKFORCE_SCHEDULE_SEGMENT_MODES")
    expect(api).not.toContain('optString("latitude")')
    expect(api).not.toContain('optString("longitude")')
    expect(activity).toContain("WorkforceScheduledContext(today.workday?.schedule?.segment)")
    expect(activity).toContain("R.string.scheduled_context_not_presence_proof")
    for (const catalog of [defaultStrings, russianStrings, azerbaijaniStrings]) {
      expect(catalog).toContain('name="scheduled_context_value"')
      expect(catalog).toContain('name="scheduled_context_not_presence_proof"')
    }
  })

  it("keeps a bounded encrypted Room outbox in domain order and isolates account changes", () => {
    const rootBuild = read("build.gradle.kts")
    const build = read("app/build.gradle.kts")
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const secureStore = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSecureStore.kt")
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const keyManager = read("app/src/main/java/com/leaddrive/workforce/android/security/WorkforceDeviceKeyManager.kt")
    expect(build).toContain('id("com.google.devtools.ksp")')
    expect(build).toContain('implementation("androidx.room:room-runtime:2.8.4")')
    expect(build).toContain('ksp("androidx.room:room-compiler:2.8.4")')
    expect(rootBuild).toContain('id("org.jetbrains.kotlin.plugin.compose") version "2.4.20"')
    expect(rootBuild).toContain('id("com.google.devtools.ksp") version "2.3.12"')
    expect(outbox).toContain("AES/GCM/NoPadding")
    expect(outbox).toContain("cipher.updateAAD")
    expect(outbox).toContain("OFFLINE_HORIZON_MS = 7 * 24 * 60 * 60 * 1_000L")
    expect(outbox).toContain("MAX_ATTEMPTS = 8")
    expect(outbox).toContain("Read the absolute oldest pending item")
    expect(outbox).toContain("oldestPending(session.accountScope, domain.name)")
    expect(outbox).not.toContain("nextAttemptAtEpochMs <= :nowEpochMs")
    expect(outbox).toContain("ACCOUNT_BOUNDARY_MUTEX.withLock")
    expect(outbox).toContain("stored.operation.domain != domain")
    expect(outbox).toContain("OUTBOX_DOMAIN_MISMATCH")
    expect(outbox).toContain("Random.Default.nextLong")
    expect(outbox).toContain("nextPendingAttemptAtEpochMs")
    expect(outbox).toContain("early wake cannot strand it")
    expect(outbox).toContain("ExistingWorkPolicy.KEEP")
    expect(outbox).toContain("NetworkType.CONNECTED")
    expect(outbox).toContain("clearForAccountBoundary")
    expect(outbox).toContain("Ephemeral attendance proof cannot enter the durable outbox")
    expect(outbox).not.toMatch(/qrToken|latitude|longitude|password|biometricTemplate/i)
    expect(repository).toContain("outbox.clearForAccountBoundary()")
    expect(repository).toContain("sessionMutex.withLock")
    expect(outbox).toContain("accountScope")
    expect(outbox).toContain("deleteLegacyUnscopedRows")
    expect(outbox).toContain("isSessionCurrent")
    expect(outbox).toContain("Migration(1, 2)")
    expect(repository).toContain("outbox.recoveryItems(session)")
    expect(secureStore).toContain("PREFERENCE_ACCOUNT_SCOPE")
    expect(secureStore).toContain("newAccountScope")
    expect(api).toContain('put("accountScope", session.accountScope)')
    expect(keyManager).toContain("createStrongBoxPreferredEnrollmentKey")
    expect(keyManager).toContain("@RequiresApi(Build.VERSION_CODES.P)")
  })

  it("keeps Work Time history on the self-HRM server lane and labels it as accepted truth", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const catalogs = [
      read("app/src/main/res/values/strings.xml"),
      read("app/src/main/res/values-ru/strings.xml"),
      read("app/src/main/res/values-az/strings.xml"),
    ]
    expect(api).toContain('"/api/v1/mtm/mobile/hrm?start=$start&end=$end"')
    expect(api).toContain("HISTORY_DAYS_BEFORE")
    expect(api).not.toContain('"/api/v1/mtm/mobile/location')
    expect(activity).toContain("R.string.history_range")
    expect(activity).toContain("R.string.history_empty_explainer")
    expect(api).toContain("WorkforceHistoryDayDetail")
    expect(api).toContain('optJSONObject("history")')
    expect(activity).toContain("R.string.history_detail_title")
    expect(activity).toContain("R.string.history_review_pending")
    expect(activity).not.toMatch(/history.*latitude|history.*longitude|history.*reasonCode/i)
    for (const catalog of catalogs) {
      expect(catalog).toContain('name="history_detail_show"')
      expect(catalog).toContain('name="history_review_pending"')
      expect(catalog).toContain('name="history_correction"')
    }
  })

  it("supports leave, absence and correction requests without putting their reason in ordinary diagnostics", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    expect(api).toContain('override val entity = "hrmRequests"')
    expect(api).toContain("WorkforceHrmRequestType")
    expect(api).toContain("WorkforceHrmRequestStatus")
    expect(api).toContain("WorkforceHrmRequestTimelineEntry")
    expect(api).toContain("WorkforceHistoryRequestState")
    expect(api).toContain('"/api/v1/mtm/mobile/hrm/exceptions"')
    expect(api).toContain("WorkforceSelfException")
    expect(api).toContain('put("exceptionCaseId", it)')
    expect(api).toContain("MAX_HRM_REQUEST_DAYS = 366L")
    expect(api).toContain("Requested finish must be after requested start")
    expect(api).toContain("toOptionalInstant")
    expect(outbox).toContain("HRM_REQUEST")
    expect(activity).toContain('var reason by remember { mutableStateOf("") }')
    expect(activity).not.toContain("var reason by rememberSaveable")
    expect(activity).toContain("R.string.requests_explainer")
    expect(activity).toContain("R.string.request_reason")
    expect(activity).toContain("R.string.request_summary")
    expect(activity).toContain("R.string.request_timeline_submitted")
    expect(activity).toContain("R.string.request_status_unknown")
    expect(activity).toContain("R.string.exception_corrections_explainer")
    expect(activity).toContain("exceptionCaseId = exception.caseId")
    expect(activity).toContain("if (correctionWorkdayId != day.workday!!.id) exceptionCaseId = \"\"")
    expect(activity).toContain("ownExceptions.isEmpty()")
    expect(activity).not.toContain("emptyList() ->")
    expect(activity).not.toContain('Text("${request.type}: ${request.status}"')
    expect(activity).not.toMatch(/Log\.|println\(|Timber\./)
  })

  it("contains an explicit foreground-only, action-time location primitive without activating background tracking", () => {
    const manifest = read("app/src/main/AndroidManifest.xml")
    const capture = read("app/src/main/java/com/leaddrive/workforce/android/location/WorkforceActionTimeLocationCapture.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const catalogs = [
      read("app/src/main/res/values/strings.xml"),
      read("app/src/main/res/values-ru/strings.xml"),
      read("app/src/main/res/values-az/strings.xml"),
    ]
    expect(capture).toContain("getCurrentLocation")
    expect(capture).toContain('@SuppressLint("MissingPermission")')
    expect(capture).toContain("ContextCompat.getMainExecutor(applicationContext)")
    expect(capture).toContain("@RequiresApi(Build.VERSION_CODES.R)")
    expect(capture).toContain("PermissionMissing")
    expect(capture).toContain("UnsupportedPlatform")
    expect(capture).toContain("CAPTURE_TIMEOUT_MS = 15_000L")
    expect(capture).toContain("MAX_LOCATION_AGE_MS = 30_000L")
    expect(capture).toContain("No legacy last-known fallback")
    expect(capture).toContain("isFromMockProvider")
    expect(api).toContain('optStringList("locationRequiredActions")')
    expect(api).toContain("fun requiresLocation")
    expect(api).toContain("WORKFORCE_WORKDAY_SCHEMA_VERSION = 4")
    expect(api).toContain('put("location", JSONObject()')
    expect(api).toContain("data.has(\"attendance\")")
    expect(repository).toContain("attendanceLocationProof")
    expect(repository).toContain("place raw coordinates in the outbox")
    expect(activity).toContain("captureLocationThenContinue")
    expect(activity).toContain("RequestMultiplePermissions")
    expect(activity).toContain("pendingLocationPermissionAction")
    expect(activity).toContain("WORKFORCE_ATTENDANCE_LOCATION_REQUIRED")
    expect(activity).toContain("WORKFORCE_ATTENDANCE_LOCATION_REVIEW_REQUIRED")
    expect(capture).not.toMatch(/requestLocationUpdates|ForegroundService|ACCESS_BACKGROUND_LOCATION/i)
    expect(manifest).not.toContain("ACCESS_BACKGROUND_LOCATION")
    expect(activity).toContain("R.string.today_location_disclaimer")
    for (const catalog of catalogs) {
      expect(catalog).toContain('name="status_capturing_location"')
      expect(catalog).toContain('name="error_location_permission_missing"')
      expect(catalog).toContain('name="error_location_provider_disabled"')
      expect(catalog).toContain('name="error_location_unavailable"')
      expect(catalog).toContain('name="error_location_unsupported"')
      expect(catalog).toContain('name="error_location_server_required"')
      expect(catalog).toContain('name="error_location_server_review_required"')
    }
  })

  it("scans a fresh QR only for the immediately requested action and never persists it", () => {
    const build = read("app/build.gradle.kts")
    const manifest = read("app/src/main/AndroidManifest.xml")
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const scanner = read("app/src/main/java/com/leaddrive/workforce/android/security/WorkforceQrScanner.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const catalogs = [
      read("app/src/main/res/values/strings.xml"),
      read("app/src/main/res/values-ru/strings.xml"),
      read("app/src/main/res/values-az/strings.xml"),
    ]
    expect(build).toContain('implementation("com.google.android.gms:play-services-code-scanner:16.1.0")')
    expect(manifest).toContain("barcode_ui")
    expect(manifest).not.toContain("android.permission.CAMERA")
    expect(scanner).toContain("Barcode.FORMAT_QR_CODE")
    expect(scanner).toContain("GmsBarcodeScanning")
    expect(scanner).not.toMatch(/SharedPreferences|Room|Log\.|println\(/)
    expect(api).toContain('put("qrToken", it)')
    expect(api).toContain("data.has(\"attendance\")")
    expect(api).toContain('optInt("enforcementVersion", 0) == 1')
    expect(api).toContain("WorkforceAttendanceRequirements.invalid()")
    expect(repository).toContain("hasEphemeralProof")
    expect(repository).toContain("error.isEligibleForOfflineOutbox()")
    expect(outbox).toContain("Ephemeral attendance proof cannot enter the durable outbox")
    expect(activity).toContain("R.string.action_scan_fresh")
    expect(activity).toContain("R.string.today_attendance_unavailable")
    expect(activity).toContain('var password by remember { mutableStateOf("") }')
    expect(activity).not.toContain("var password by rememberSaveable")
    expect(activity).toContain("activeQrScanAttemptId")
    expect(activity).toContain("R.string.action_scanning")
    for (const catalog of catalogs) expect(catalog).toContain('name="action_scanning"')
  })

  it("has a metadata-only recovery center with explicit safe next steps", () => {
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const catalogs = [
      read("app/src/main/res/values/strings.xml"),
      read("app/src/main/res/values-ru/strings.xml"),
      read("app/src/main/res/values-az/strings.xml"),
    ]
    expect(outbox).toContain("Metadata-only recovery view")
    expect(outbox).toContain("OFFLINE_HORIZON_EXPIRED")
    expect(outbox).toContain("WorkforceOutboxRecoveryHint.OFFLINE_LIMIT_EXPIRED")
    expect(outbox).toContain("MTM_MOBILE_SYNC_OPERATION_TOO_LARGE")
    expect(outbox).toContain("MTM_MOBILE_SYNC_OPERATION_INVALID")
    expect(outbox).toContain("WorkforceOutboxRecoveryHint.QUARANTINED_OPERATION")
    expect(outbox).not.toContain("Request a correction instead of retrying")
    expect(outbox).toContain("SELECT domain, state, createdAtEpochMs, detailCode FROM workforce_outbox_operations")
    expect(outbox).not.toContain("SELECT ciphertext")
    expect(outbox).toContain("ACCOUNT_BOUNDARY_MUTEX.withLock")
    expect(repository).toContain("loadRecoveryItems")
    expect(repository).toContain("sessionMutex.withLock")
    expect(activity).toContain("atZone(tenantZone)")
    expect(activity).not.toContain("ZoneId.systemDefault()")
    expect(activity).toContain("R.string.recovery_explainer")
    expect(activity).toContain("R.string.recovery_hint_offline_limit_expired")
    expect(activity).toContain("R.string.recovery_hint_quarantined_operation")
    for (const catalog of catalogs) {
      expect(catalog).toContain('name="recovery_hint_quarantined_operation"')
    }
  })

  it("uses a per-use non-exportable Android key and OS-owned strong-biometric signature without handling biometric data", () => {
    const build = read("app/build.gradle.kts")
    const deviceKey = read("app/src/main/java/com/leaddrive/workforce/android/security/WorkforceDeviceKeyManager.kt")
    const authenticator = read("app/src/main/java/com/leaddrive/workforce/android/security/WorkforceDeviceAuthenticator.kt")
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const defaultStrings = read("app/src/main/res/values/strings.xml")
    const russianStrings = read("app/src/main/res/values-ru/strings.xml")
    const azerbaijaniStrings = read("app/src/main/res/values-az/strings.xml")
    expect(build).toContain('implementation("androidx.biometric:biometric:1.1.0")')
    expect(deviceKey).toContain("setAttestationChallenge(challenge)")
    expect(deviceKey).toContain("setUserAuthenticationRequired(true)")
    expect(deviceKey).toContain("setUserAuthenticationParameters")
    expect(deviceKey).toContain("createStrongBoxPreferredEnrollmentKey")
    expect(deviceKey).toContain("@RequiresApi(Build.VERSION_CODES.P)")
    expect(deviceKey).toContain("KeyProperties.AUTH_BIOMETRIC_STRONG")
    expect(deviceKey).not.toContain("AUTH_DEVICE_CREDENTIAL")
    expect(deviceKey).toContain("KeyProperties.KEY_ALGORITHM_EC")
    expect(deviceKey).toContain("prepareCanonicalActionSignature")
    expect(authenticator).toContain("BiometricPrompt.CryptoObject(signature)")
    expect(authenticator).toContain("BiometricManager.Authenticators.BIOMETRIC_STRONG")
    expect(authenticator).toContain("setNegativeButtonText(activity.getString(R.string.cancel))")
    expect(authenticator).not.toMatch(/FingerprintManager|faceTemplate|biometricTemplate|upload/i)
    expect(api).toContain('"/api/v1/mtm/mobile/attendance/devices/enrollments"')
    expect(api).toContain('"/api/v1/mtm/mobile/attendance/devices/enrollments/${enrollmentId}/proof"')
    expect(api).toContain('"/api/v1/mtm/mobile/attendance/devices/enrollments/${enrollmentId}/revoke"')
    expect(api).toContain('put("device", JSONObject()')
    expect(api).toContain("truncatedTo(ChronoUnit.MILLIS)")
    expect(repository).toContain("workforce-device-enrollment:v1")
    expect(repository).toContain("workforce-device-attendance:v1")
    expect(repository).toContain("never eligible for offline storage")
    expect(repository).toContain("sessionMutex.withLock")
    expect(repository).toContain("runCatching { deviceKeys.delete(alias) }")
    expect(api).toContain("requiresDeviceProof")
    expect(repository).toContain("revokeOwnDeviceEnrollment")
    expect(repository).toContain("private key is deleted only after the server acknowledges revocation")
    expect(activity).toContain("R.string.action_scan_and_confirm")
    expect(activity).toContain("R.string.qr_scan_cancelled")
    expect(activity).toContain("R.string.qr_scan_unreadable")
    expect(activity).toContain("R.string.device_trust_title")
    expect(activity).toContain("R.string.device_revoke_dialog_title")
    expect(activity).toContain("deviceLifecycleMessage")
    expect(activity).toContain("deviceEnrollmentStatus")
    expect(activity).toContain("val defaultDeviceLabel = stringResource")
    expect(activity).not.toContain("mutableStateOf(stringResource")
    for (const catalog of [defaultStrings, russianStrings, azerbaijaniStrings]) {
      expect(catalog).toContain('name="device_trust_explainer"')
      expect(catalog).toContain('name="device_revoke_dialog_body"')
      expect(catalog).toContain('name="device_state_pending_manager_approval"')
      expect(catalog).toContain('name="qr_scan_cancelled"')
      expect(catalog).toContain('name="qr_scan_unreadable"')
    }
  })

  it("bounds pull-request Android CI to the affected paths and cancels superseded work", () => {
    const workflow = readFileSync(resolve(process.cwd(), ".github/workflows/workforce-android.yml"), "utf8")
    expect(workflow).toContain("pull_request:")
    expect(workflow).toContain('      - "apps/workforce-android/**"')
    expect(workflow).toContain("concurrency:")
    expect(workflow).toContain("cancel-in-progress: true")
    expect(workflow).toContain("runs-on: ubuntu-24.04")
  })

  it("keeps optional local reminders generic, server-snapshotted and free of employee identifiers", () => {
    const store = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSecureStore.kt")
    const scheduler = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceReminderScheduler.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    expect(store).toContain("localRemindersEnabled")
    expect(scheduler).toContain("workday?.schedule?.plannedEndAt")
    expect(scheduler).toContain("Data.EMPTY")
    expect(scheduler).toContain("POST_NOTIFICATIONS")
    expect(scheduler).toContain('@SuppressLint("MissingPermission")')
    expect(scheduler).toContain("R.string.notification_text")
    expect(scheduler).toContain("WORK_NAME = \"workforce-local-reminder\"")
    expect(scheduler).not.toMatch(/09:00|18:00|Asia\/Baku|qrToken|latitude|longitude|employeeName|workdayId/)
    expect(scheduler).not.toContain("Result.retry()")
    expect(repository).toContain("reminderScheduler.cancelAll()")
    expect(repository).toContain("setLocalRemindersEnabled")
    expect(activity).toContain("R.string.turn_on_reminders")
    expect(activity).toContain("RequestPermission()")
  })

  it("has an AZ/RU/EN resource foundation and source-level Compose accessibility semantics", () => {
    const defaultStrings = read("app/src/main/res/values/strings.xml")
    const russianStrings = read("app/src/main/res/values-ru/strings.xml")
    const azerbaijaniStrings = read("app/src/main/res/values-az/strings.xml")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const reminders = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceReminderScheduler.kt")
    const authenticator = read("app/src/main/java/com/leaddrive/workforce/android/security/WorkforceDeviceAuthenticator.kt")
    for (const catalog of [defaultStrings, russianStrings, azerbaijaniStrings]) {
      expect(catalog).toContain('name="tab_today"')
      expect(catalog).toContain('name="turn_on_reminders"')
      expect(catalog).toContain('name="notification_text"')
      expect(catalog).toContain('name="biometric_title"')
    }
    expect(activity).toContain("stringResource")
    expect(activity).toContain("selectableGroup()")
    expect(activity).toContain("role = Role.Tab")
    expect(activity).toContain("stateDescription = selectionState")
    expect(activity).toContain("liveRegion = LiveRegionMode.Polite")
    expect(activity).toContain("defaultMinSize")
    expect(activity).toContain("minWidth = 48.dp")
    expect(activity).toContain("minHeight = 48.dp")
    expect(reminders).toContain("R.string.notification_text")
    expect(authenticator).toContain("R.string.biometric_title")
    expect(authenticator).toContain("R.string.cancel")
  })

  it("uses localized generic status and failure copy instead of reflecting API/device messages", () => {
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const catalogs = [
      read("app/src/main/res/values/strings.xml"),
      read("app/src/main/res/values-ru/strings.xml"),
      read("app/src/main/res/values-az/strings.xml"),
    ]
    expect(activity).toContain("WorkforceEmployeeErrorCopy")
    expect(activity).toContain("is WorkforceApiException -> when (recoveryCode)")
    expect(activity).toContain("else -> copy.api")
    expect(activity).not.toContain("is WorkforceApiException -> message")
    expect(activity).toContain("val deviceActionPrompts = mapOf")
    expect(activity).toContain("val deviceEnrollmentPromptTemplate = stringResource")
    expect(activity).toContain("val deviceLifecycleMessages = mapOf<WorkforceDeviceBindingLifecycle?, String>")
    expect(activity).not.toContain("context.getString(R.string.device_action_prompt")
    expect(activity).not.toContain("context.getString(R.string.device_enrollment_prompt")
    expect(activity).not.toContain("context.getString(deviceLifecycleMessage")
    expect(activity).toContain("R.string.device_action_prompt")
    expect(activity).toContain("R.string.device_enrollment_prompt")
    expect(repository).not.toContain("val message: String")
    expect(repository).not.toContain("employeeMessage")
    for (const catalog of catalogs) {
      expect(catalog).toContain('name="status_today_queued"')
      expect(catalog).toContain('name="status_request_accepted"')
      expect(catalog).toContain('name="error_action_conflict"')
      expect(catalog).toContain('name="error_request_failed"')
      expect(catalog).toContain('name="error_network_unavailable"')
      expect(catalog).toContain('name="device_action_prompt"')
      expect(catalog).toContain('name="device_enrollment_prompt"')
    }
  })

  it("sends only bounded release and coarse device diagnostics through the existing sync observability path", () => {
    const build = read("app/build.gradle.kts")
    const configuration = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceRuntimeConfiguration.kt")
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    expect(build).toContain("WORKFORCE_BUILD_SHA")
    expect(build).toContain('Regex("[0-9a-f]{40}")')
    expect(configuration).toContain("WorkforceDeviceClass")
    expect(configuration).toContain("SCREENLAYOUT_SIZE_MASK")
    expect(configuration).not.toMatch(/Build\.(MODEL|SERIAL)|Settings\.Secure\.ANDROID_ID/i)
    expect(api).toContain('"x-workforce-app-build"')
    expect(api).toContain('"x-workforce-device-class"')
    expect(api).not.toMatch(/Log\.|println\(/)
  })

  it("fails closed for a required managed-Play update while preserving the encrypted outbox for a supported resume", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const defaultStrings = read("app/src/main/res/values/strings.xml")
    const russianStrings = read("app/src/main/res/values-ru/strings.xml")
    const azerbaijaniStrings = read("app/src/main/res/values-az/strings.xml")
    expect(api).toContain("WorkforceMobileReleaseStatus")
    expect(api).toContain("UNKNOWN(true)")
    expect(api).toContain("blockWorkforceMutations")
    expect(api).toContain("parsed.scheme == \"https\"")
    expect(repository).toContain("requireMutableRelease")
    expect(repository).toContain("outbox.resumeDrain()")
    expect(outbox).toContain("deferForMandatoryUpdate")
    expect(outbox).toContain("WORKFORCE_MOBILE_UPDATE_REQUIRED")
    expect(outbox).toContain("fromBuildConfig(applicationContext)")
    expect(activity).toContain("mutationsBlocked = bootstrap.release.mutationsBlocked")
    expect(activity).toContain("enabled = busyAction == null && !mutationsBlocked")
    expect(activity).toContain("R.string.device_lost_guidance")
    expect(activity).toContain("R.string.device_uninstall_guidance")
    for (const catalog of [defaultStrings, russianStrings, azerbaijaniStrings]) {
      expect(catalog).toContain('name="update_required_before_changes"')
      expect(catalog).toContain('name="device_lost_guidance"')
      expect(catalog).toContain('name="device_uninstall_guidance"')
    }
  })
})
