import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"

const androidRoot = resolve(process.cwd(), "apps/workforce-android")
const read = (path: string) => readFileSync(resolve(androidRoot, path), "utf8")

describe("Workforce Android foundation", () => {
  it("keeps the source project Android-first and refuses an implicit production release identity", () => {
    const build = read("app/build.gradle.kts")
    expect(build).toContain("id(\"com.android.application\")")
    expect(build).toContain("id(\"org.jetbrains.kotlin.plugin.compose\")")
    expect(build).toContain("compileSdk = 37")
    expect(build).toContain("WORKFORCE_APPLICATION_ID")
    expect(build).toContain("invalid.release.workforce")
    expect(build).toContain("WORKFORCE_API_BASE_URL")
    expect(build).not.toMatch(/applicationId\s*=\s*\"com\.leaddrive\.workforce\"/)
  })

  it("does not declare background location or backup of employee session data", () => {
    const manifest = read("app/src/main/AndroidManifest.xml")
    const dataRules = read("app/src/main/res/xml/data_extraction_rules.xml")
    expect(manifest).toContain("ACCESS_FINE_LOCATION")
    expect(manifest).toContain("barcode_ui")
    expect(manifest).not.toContain("android.permission.CAMERA")
    expect(manifest).not.toContain("ACCESS_BACKGROUND_LOCATION")
    expect(manifest).not.toContain("foregroundServiceType=\"location\"")
    expect(manifest).toContain("android:allowBackup=\"false\"")
    expect(dataRules).toContain("<exclude domain=\"sharedpref\" path=\".\" />")
    expect(dataRules).toContain("<exclude domain=\"database\" path=\".\" />")
  })

  it("keeps the Android data layer limited to Workforce login, server-truth work time and secure local session state", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const store = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSecureStore.kt")
    expect(api).toContain('"/api/v1/mtm/mobile/auth"')
    expect(api).toContain('"/api/v1/mtm/mobile/bootstrap"')
    expect(api).toContain('"/api/v1/mtm/mobile/workday"')
    expect(api).toContain('"/api/v1/mtm/mobile/sync/push"')
    expect(api).toContain('override val entity = "workdays"')
    expect(api).toContain('"schemaVersion", WORKFORCE_WORKDAY_SCHEMA_VERSION')
    expect(api).toContain("UUID.randomUUID()")
    expect(api).toContain("if (activeWorkday == null)")
    expect(api).not.toContain('"/api/v1/mtm/mobile/routes')
    expect(api).not.toContain('"/api/v1/mtm/mobile/visits')
    expect(api).toContain('"x-workforce-client"')
    expect(api).toContain('"x-workforce-app-version-code"')
    expect(store).toContain("AndroidKeyStore")
    expect(store).toContain("AES/GCM/NoPadding")
    expect(store).toContain("clearForLogout")
  })

  it("restores canonical Today state after process death and never manufactures an offline fact", () => {
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    expect(activity).toContain("LaunchedEffect(Unit)")
    expect(activity).toContain("repository.restore()")
    expect(activity).toContain("repository.loadToday()")
    expect(activity).toContain("No attendance action was created locally")
    expect(activity).toContain("it is not a server-accepted fact")
    expect(repository).toContain("submitTodayAction")
  })

  it("keeps a bounded encrypted Room outbox in domain order and isolates account changes", () => {
    const rootBuild = read("build.gradle.kts")
    const build = read("app/build.gradle.kts")
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    expect(build).toContain('id("com.google.devtools.ksp")')
    expect(build).toContain('implementation("androidx.room:room-runtime:2.8.4")')
    expect(build).toContain('ksp("androidx.room:room-compiler:2.8.4")')
    expect(rootBuild).toContain('id("org.jetbrains.kotlin.plugin.compose") version "2.4.20"')
    expect(rootBuild).toContain('id("com.google.devtools.ksp") version "2.3.12"')
    expect(outbox).toContain("AES/GCM/NoPadding")
    expect(outbox).toContain("cipher.updateAAD")
    expect(outbox).toContain("OFFLINE_HORIZON_MS = 7 * 24 * 60 * 60 * 1_000L")
    expect(outbox).toContain("MAX_ATTEMPTS = 8")
    expect(outbox).toContain("Read the absolute oldest pending item")
    expect(outbox).toContain("oldestPending(domain.name)")
    expect(outbox).not.toContain("nextAttemptAtEpochMs <= :nowEpochMs")
    expect(outbox).toContain("ACCOUNT_BOUNDARY_MUTEX.withLock")
    expect(outbox).toContain("stored.operation.domain != domain")
    expect(outbox).toContain("OUTBOX_DOMAIN_MISMATCH")
    expect(outbox).toContain("ExistingWorkPolicy.KEEP")
    expect(outbox).toContain("NetworkType.CONNECTED")
    expect(outbox).toContain("clearForAccountBoundary")
    expect(outbox).not.toMatch(/qrToken|latitude|longitude|password|biometricTemplate/i)
    expect(repository).toContain("outbox.clearForAccountBoundary()")
    expect(repository).toContain("sessionMutex.withLock")
  })

  it("keeps Work Time history on the self-HRM server lane and labels it as accepted truth", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    expect(api).toContain('"/api/v1/mtm/mobile/hrm?start=$start&end=$end"')
    expect(api).toContain("HISTORY_DAYS_BEFORE")
    expect(api).not.toContain('"/api/v1/mtm/mobile/location')
    expect(activity).toContain("Accepted server history")
    expect(activity).toContain("A local pending claim is never presented as an accepted fact")
  })

  it("supports leave, absence and correction requests without putting their reason in ordinary diagnostics", () => {
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    expect(api).toContain('override val entity = "hrmRequests"')
    expect(api).toContain("WorkforceHrmRequestType")
    expect(api).toContain("MAX_HRM_REQUEST_DAYS = 366L")
    expect(api).toContain("Requested finish must be after requested start")
    expect(api).toContain("toOptionalInstant")
    expect(outbox).toContain("HRM_REQUEST")
    expect(activity).toContain("Leave, absence and correction requests")
    expect(activity).toContain("Reason (visible only to the responsible reviewers)")
    expect(activity).toContain('var reason by remember { mutableStateOf("") }')
    expect(activity).not.toContain("var reason by rememberSaveable")
    expect(activity).not.toMatch(/Log\.|println\(|Timber\./)
  })

  it("contains an explicit foreground-only, action-time location primitive without activating background tracking", () => {
    const manifest = read("app/src/main/AndroidManifest.xml")
    const capture = read("app/src/main/java/com/leaddrive/workforce/android/location/WorkforceActionTimeLocationCapture.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    expect(capture).toContain("getCurrentLocation")
    expect(capture).toContain("PermissionMissing")
    expect(capture).toContain("UnsupportedPlatform")
    expect(capture).toContain("CAPTURE_TIMEOUT_MS = 15_000L")
    expect(capture).toContain("MAX_LOCATION_AGE_MS = 30_000L")
    expect(capture).toContain("No legacy last-known fallback")
    expect(capture).not.toMatch(/requestLocationUpdates|ForegroundService|ACCESS_BACKGROUND_LOCATION/i)
    expect(manifest).not.toContain("ACCESS_BACKGROUND_LOCATION")
    expect(activity).toContain("never tracked in the background")
    expect(activity).toContain("legal notice and tenant proof policy are active")
  })

  it("scans a fresh QR only for the immediately requested action and never persists it", () => {
    const build = read("app/build.gradle.kts")
    const manifest = read("app/src/main/AndroidManifest.xml")
    const api = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceApiClient.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const scanner = read("app/src/main/java/com/leaddrive/workforce/android/security/WorkforceQrScanner.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    expect(build).toContain('implementation("com.google.android.gms:play-services-code-scanner:16.1.0")')
    expect(manifest).toContain("barcode_ui")
    expect(manifest).not.toContain("android.permission.CAMERA")
    expect(scanner).toContain("Barcode.FORMAT_QR_CODE")
    expect(scanner).toContain("GmsBarcodeScanning")
    expect(scanner).not.toMatch(/SharedPreferences|Room|Log\.|println\(/)
    expect(api).toContain('put("qrToken", it)')
    expect(api).toContain("data.has(\"attendance\")")
    expect(api).toContain('optInt("enforcementVersion", 0) == 1')
    expect(api).toContain("WorkforceAttendanceRequirements.invalid()")
    expect(repository).toContain("hasEphemeralProof")
    expect(repository).toContain("error.isEligibleForOfflineOutbox()")
    expect(outbox).toContain("Ephemeral attendance proof cannot enter the durable outbox")
    expect(activity).toContain("Scan fresh QR")
    expect(activity).toContain("Attendance policy is unavailable or unsupported")
  })

  it("has a metadata-only recovery center with explicit safe next steps", () => {
    const outbox = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceEncryptedOutbox.kt")
    const repository = read("app/src/main/java/com/leaddrive/workforce/android/data/WorkforceSessionRepository.kt")
    const activity = read("app/src/main/java/com/leaddrive/workforce/android/MainActivity.kt")
    expect(outbox).toContain("Metadata-only recovery view")
    expect(outbox).toContain("OFFLINE_HORIZON_EXPIRED")
    expect(outbox).toContain("Request a correction instead of retrying")
    expect(outbox).toContain("SELECT domain, state, createdAtEpochMs, detailCode FROM workforce_outbox_operations")
    expect(outbox).not.toContain("SELECT ciphertext")
    expect(outbox).toContain("ACCOUNT_BOUNDARY_MUTEX.withLock")
    expect(repository).toContain("loadRecoveryItems")
    expect(repository).toContain("sessionMutex.withLock")
    expect(activity).toContain("This view shows only local queue state")
    expect(activity).toContain("never request reasons, QR values, GPS or device proof")
    expect(activity).toContain("atZone(tenantZone)")
    expect(activity).not.toContain("ZoneId.systemDefault()")
  })

  it("uses an attested non-exportable Android key without handling biometric data", () => {
    const deviceKey = read("app/src/main/java/com/leaddrive/workforce/android/security/WorkforceDeviceKeyManager.kt")
    expect(deviceKey).toContain("setAttestationChallenge(challenge)")
    expect(deviceKey).toContain("setUserAuthenticationRequired(true)")
    expect(deviceKey).toContain("setUserAuthenticationParameters")
    expect(deviceKey).toContain("KeyProperties.KEY_ALGORITHM_EC")
    expect(deviceKey).not.toMatch(/BiometricPrompt|FingerprintManager|faceTemplate|biometricTemplate/i)
  })

  it("bounds pull-request Android CI to the affected paths and cancels superseded work", () => {
    const workflow = readFileSync(resolve(process.cwd(), ".github/workflows/workforce-android.yml"), "utf8")
    expect(workflow).toContain("pull_request:")
    expect(workflow).toContain('      - "apps/workforce-android/**"')
    expect(workflow).toContain("concurrency:")
    expect(workflow).toContain("cancel-in-progress: true")
    expect(workflow).toContain("runs-on: ubuntu-24.04")
  })
})
