/**
 * Scenario «prospect-to-closed-won», version 1.
 *
 * The prospect who filled the /demo form becomes their own lead and moves it
 * through the real LeadDrive screens: campaign → inbox conversation → AI
 * draft → lead → qualification → (call: disabled in v1) → task → deal →
 * quote → closed won. Only four sidebar groups are visible.
 *
 * All prospect-facing copy is Azerbaijani. Every action step completes only
 * when the journey state or the session snapshot actually changes.
 */
import type { DemoJourneyManifest } from "./types"

export const PROSPECT_TO_CLOSED_WON: DemoJourneyManifest = {
  scenarioId: "prospect-to-closed-won",
  version: 1,
  locale: "az",
  title: "İlk lidiniz: müraciətdən sövdələşməyə",
  summary:
    "Siz özünüz LeadDrive-da lid olursunuz və öz hekayənizi izləyirsiniz: kampaniya, yazışma, AI cavabı, lid, tapşırıq, sövdələşmə, kommersiya təklifi və qazanılmış nəticə.",
  navGroups: ["crm", "sales", "omnichannel", "marketing"],
  visibleRoutes: [
    "/campaigns",
    "/inbox",
    "/leads",
    "/boards",
    "/deals",
    "/quotes",
  ],
  capabilities: {
    emailVerification: true,
    phoneVerification: false,
    liveCall: false,
    video: true,
    narration: false,
    // Owner decision 2026-09-20: on, 50 questions per session, Sonnet. The
    // assistant explains the screen and the story; commercial questions are
    // refused by policy rather than improvised (assistant/policy.ts).
    assistant: true,
  },
  estimatedMinutes: 28,
  sections: [
    {
      id: "orientation",
      title: "Bu, LeadDrive-dır",
      summary: "Burada gördüyünüz hər şey real məhsuldur. Bütün qeydlər nümunədir və yalnız bu sessiya üçün yaradılıb.",
      area: "shell",
      route: "demo:orientation",
      navGroup: "demo",
      estimatedMinutes: 1,
      requires: [],
      entryStates: ["STARTED"],
      exitStates: ["STARTED"],
      steps: [
        {
          id: "orientation-sidebar",
          title: "Solda — dörd bölmə",
          instruction: "Bu demo üçün sizə dörd bölmə açılıb: Əsas, Satış, Kommunikasiya və Marketinq. Qalan modullar bilərəkdən gizlədilib ki, hekayəni itirməyəsiniz.",
          anchor: "demo-sidebar",
          placement: "right",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: [],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "orientation-guide",
          title: "Sağda — bələdçi",
          instruction: "Bu panel hər addımda nə etməli olduğunuzu göstərir. Addım yalnız real hərəkətdən sonra tamamlanmış sayılır.",
          anchor: "demo-guide-panel",
          placement: "left",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: [],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "orientation-synthetic",
          title: "Məlumatlar nümunədir",
          instruction: "Şirkətinizin adı və sizin adınız istifadə olunur, amma bütün məbləğlər, tarixlər və yazışmalar nümunədir. Heç bir real müştəri məlumatı burada yoxdur.",
          anchor: "demo-watermark",
          placement: "top",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: [],
          fallback: "Bütün qeydlər sintetikdir və sessiya bitəndə silinir.",
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "source",
      title: "Müraciətiniz haradan gəldi",
      summary: "Hər lidin mənbəyi var. Formada seçdiyiniz kanal LeadDrive-da kampaniya kimi görünür.",
      area: "campaigns",
      route: "/campaigns",
      navGroup: "marketing",
      estimatedMinutes: 2,
      requires: [],
      entryStates: ["STARTED"],
      exitStates: ["SOURCE_SEEN"],
      intro: { slug: "demo-campaigns", caption: "Kampaniyalar — kanal, alıcılar və nəticə bir dəqiqədə.", status: "available" },
      assistantPrompts: ["Bu kampaniya hansı kanalla göndərilib?", "Kampaniyanın nəticəsi necə ölçülür?"],
      steps: [
        {
          id: "source-stats",
          title: "Kampaniyaların vəziyyəti",
          instruction: "Yuxarıda kampaniyalar statuslara görə sayılır: qaralama, planlaşdırılmış, göndərilir, göndərilib.",
          anchor: "campaigns-stats",
          placement: "bottom",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["campaigns.stats", "campaigns.tabs"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "source-open-campaign",
          title: "Sizi gətirən kampaniya",
          instruction: "Siyahıda formada qeyd etdiyiniz kanala uyğun kampaniyanı görürsünüz. Onu açın.",
          anchor: "campaigns-list",
          placement: "top",
          action: "click",
          targetLabel: "Kampaniyanı açın",
          required: true,
          completion: { kind: "transition", to: "SOURCE_SEEN" },
          covers: ["campaigns.list", "campaigns.detail"],
          result: "Kampaniya açıldı. Bu kampaniya sizin lidinizin mənbəyi kimi qeyd olunacaq.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "source-analytics",
          title: "Nə işlədi",
          // The rates here are the session's fixed sample (records.ts), whatever
          // channel the prospect chose. In the product only email campaigns record
          // opens and clicks (src/lib/campaigns/analytics.ts), so the copy says so.
          instruction: "Kampaniyanın açılma və klik faizi — burada nümunə rəqəmlərdir. Real hesabda açılma və klikləri e-poçt kampaniyaları qeydə alır, «Analitika» vərəqi isə onları bütün kampaniyalar üzrə ümumiləşdirir.",
          anchor: "campaigns-analytics",
          placement: "bottom",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["campaigns.analytics"],
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "conversation",
      title: "Gələnlər qutusunda dialoqunuz",
      summary: "Müştəri hansı kanaldan yazsa da — WhatsApp, Instagram, veb-çat — dialoq bir yerdə toplanır.",
      area: "inbox",
      route: "/inbox",
      navGroup: "omnichannel",
      estimatedMinutes: 3,
      requires: [],
      entryStates: ["SOURCE_SEEN"],
      exitStates: ["CONVERSATION_OPENED"],
      intro: { slug: "demo-inbox", caption: "Gələnlər qutusu — bütün kanallar bir siyahıda.", status: "available" },
      assistantPrompts: ["Hansı kanallar dəstəklənir?", "Cavab verilməmiş dialoqları necə taparam?"],
      steps: [
        {
          id: "conversation-views",
          title: "Kimin dialoqları",
          instruction: "Solda görünüşlər: Hamısı, Mənim, Məsul yoxdur, Çat-bot. Menecer öz növbəsini bir kliklə görür.",
          anchor: "inbox-views",
          placement: "right",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["inbox.views", "inbox.status-tabs", "inbox.filters"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "conversation-open",
          title: "Sizin müraciətiniz",
          instruction: "Siyahıda öz adınızla dialoq var — bu, formada yazdığınız müraciətdir. Onu açın.",
          anchor: "inbox-conversations",
          placement: "right",
          action: "click",
          targetLabel: "Yazışmanı açın",
          required: true,
          completion: { kind: "transition", to: "CONVERSATION_OPENED" },
          covers: ["inbox.conversations", "inbox.thread"],
          result: "Dialoq açıldı: kanal, vaxt və mesaj mətni görünür.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "conversation-contact",
          title: "Kim yazır",
          instruction: "Sağ paneldə müştərinin məlumatları, teqlər və mərhələ toplanır. Menecerə başqa yerə keçmək lazım deyil.",
          anchor: "inbox-contact-panel",
          placement: "left",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["inbox.contact-panel"],
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "ai-reply",
      title: "Da Vinci cavab hazırlayır, siz təsdiqləyirsiniz",
      summary: "AI ilk cavabı yazır, amma göndərməzdən əvvəl insan yoxlayır. Heç nə nəzarətsiz getmir.",
      area: "inbox",
      route: "/inbox",
      navGroup: "omnichannel",
      estimatedMinutes: 2,
      requires: [],
      entryStates: ["CONVERSATION_OPENED"],
      exitStates: ["AI_REPLIED"],
      assistantPrompts: ["AI cavabı nəyə əsaslanır?", "AI-ın söz verməsinə necə mane olursunuz?"],
      steps: [
        {
          id: "ai-reply-draft",
          title: "Qaralama hazırdır",
          instruction: "Bu paneldə AI-ın hazırladığı cavab, onun keyfiyyət balı və niyə yoxlamaya göndərildiyi göstərilir.",
          anchor: "inbox-ai-draft",
          placement: "top",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: ["inbox.ai-draft"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "ai-reply-send",
          title: "Cavabı təsdiqləyin",
          instruction: "«Göndər» düyməsini basın. Bu demoda mesaj real kanala getmir — yalnız lentdə görünür.",
          anchor: "inbox-ai-draft",
          placement: "top",
          action: "confirm",
          targetLabel: "Cavabı göndərin",
          required: true,
          completion: { kind: "transition", to: "AI_REPLIED" },
          covers: ["inbox.ai-draft", "inbox.thread"],
          result: "Cavab lentə düşdü və «AI cavabı» nişanı ilə işarələndi (simulyasiya).",
          analyticsEvent: "journey.transition",
        },
        {
          id: "ai-reply-composer",
          title: "Əl ilə cavab da mümkündür",
          instruction: "Aşağıda kompozer: cavab və ya daxili qeyd, hazır şablonlar «/» ilə, AI-ın köməyi ilə mətni qısaltmaq və tərcümə etmək.",
          anchor: "inbox-composer",
          placement: "top",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["inbox.composer"],
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "lead-created",
      title: "Siz artıq LeadDrive-da lidsiniz",
      summary: "Dialoqdan lid kartı yaranır: ad, şirkət, vəzifə, mənbə və bütün tarixçə bir yerdə.",
      area: "leads",
      route: "/leads/[id]",
      navGroup: "sales",
      estimatedMinutes: 4,
      requires: [],
      entryStates: ["AI_REPLIED"],
      exitStates: ["LEAD_CREATED"],
      // Filmed on the synthetic `demo` stand (scripts/seeds/demo-journey-clips.mjs).
      // The help library's own leads clip shows LeadDrive Inc.'s test records
      // and stays out of the demo (2026-09-21).
      intro: { slug: "demo-leads", caption: "Lidlər siyahısı və kart — bir dəqiqəlik icmal.", status: "available" },
      assistantPrompts: ["Bu lidin mənbəyi nədir?", "Lid kartında hansı vərəqlər var?"],
      steps: [
        {
          id: "lead-list-stats",
          title: "Lidlər siyahısı",
          instruction: "Yuxarıda statistika və status filtrləri; alətlər panelində axtarış, kateqoriya, mənbə və görünüş.",
          anchor: "leads-status-filter",
          placement: "bottom",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["leads.list.header", "leads.list.stats", "leads.list.status-pills", "leads.list.toolbar", "leads.list.table"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "lead-open",
          title: "Öz kartınızı açın",
          instruction: "«Yeni» sütununda sizin adınızla kart var. Onu açın.",
          anchor: "leads-kanban",
          placement: "top",
          action: "click",
          targetLabel: "Kartınızı açın",
          required: true,
          completion: { kind: "transition", to: "LEAD_CREATED" },
          covers: ["leads.list.kanban"],
          result: "Lid kartı açıldı: ad, şirkət, vəzifə və mənbə — kampaniya — dolduruldu.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "lead-details",
          title: "Kartda nə var",
          instruction: "«Detallar» vərəqi: lidin və müştərinin məlumatları, mənbə, qeydlər. Yuxarıda əsas göstəricilər.",
          anchor: "lead-details",
          placement: "top",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: ["leads.card.details", "leads.card.overview", "leads.card.kpi", "leads.card.header"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "lead-timeline",
          title: "Tarixçə itmir",
          instruction: "«Qarşılıqlı əlaqələr» vərəqinə keçin: müraciətiniz, ona hazırlanan AI cavabı və kartın yaradılması artıq buradadır.",
          anchor: "lead-tabs",
          placement: "bottom",
          action: "click",
          targetLabel: "«Qarşılıqlı əlaqələr» tabını açın",
          required: true,
          completion: { kind: "snapshot", path: "lead.activeTab", equals: "timeline" },
          covers: ["leads.card.timeline", "leads.card.activities"],
          result: "Lentdə dialoq, AI cavabı və kartın yaradılması görünür.",
          analyticsEvent: "journey.step_completed",
        },
        {
          id: "lead-sentiment-tasks",
          title: "Əhval və tapşırıqlar",
          instruction: "«Əhval» yazışmanın tonunu göstərir, «Tapşırıqlar» — bu lidlə bağlı işləri. Hələlik boşdur; birazdan dolacaq.",
          anchor: "lead-tabs",
          placement: "bottom",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["leads.card.sentiment", "leads.card.tasks"],
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "lead-qualified",
      title: "Lid nə qədər hazırdır",
      summary: "Da Vinci lidi qiymətləndirir və növbəti addımı təklif edir; menecer statusu irəli aparır.",
      area: "leads",
      route: "/leads/[id]",
      navGroup: "sales",
      estimatedMinutes: 2,
      requires: [],
      entryStates: ["LEAD_CREATED"],
      exitStates: ["LEAD_QUALIFIED"],
      assistantPrompts: ["Bal nəyə görə hesablanır?", "Kvalifikasiya olunmuş lid nə deməkdir?"],
      steps: [
        {
          id: "lead-scoring",
          title: "Da Vinci balı",
          instruction: "«Da Vinci Reytinq» vərəqini açın: bal, səbəblər və tövsiyə olunan növbəti addım.",
          anchor: "lead-tabs",
          placement: "bottom",
          action: "click",
          targetLabel: "«Da Vinci Reytinq» tabını açın",
          required: true,
          completion: { kind: "snapshot", path: "lead.activeTab", equals: "ai" },
          covers: ["leads.card.ai-scoring"],
          result: "Bal və tövsiyə göstərildi (nümunə hesablama).",
          analyticsEvent: "journey.step_completed",
        },
        {
          id: "lead-status-advance",
          title: "Statusu irəli aparın",
          instruction: "Status zolağında «Kvalifikasiya edildi» mərhələsini seçin.",
          anchor: "lead-status-bar",
          placement: "bottom",
          action: "choose",
          targetLabel: "«Kvalifikasiya edildi» seçin",
          required: true,
          completion: { kind: "transition", to: "LEAD_QUALIFIED" },
          covers: ["leads.card.status-bar"],
          result: "Lid kvalifikasiya olundu; dəyişiklik lentə yazıldı.",
          analyticsEvent: "journey.transition",
        },
      ],
    },
    {
      id: "ai-call",
      title: "AI telefon zəngi",
      summary: "Menecer kartdan «AI ilə zəng et» basır: köməkçi zəng edir, nəticə və qeyd kartda qalır. Açıq demoda zəng simulyasiya olunur; şəxsi demoda AI həqiqətən sizin nömrənizə zəng edir.",
      area: "leads",
      route: "/leads/[id]",
      navGroup: "sales",
      estimatedMinutes: 1,
      requires: [],
      entryStates: ["LEAD_QUALIFIED"],
      exitStates: ["CALL_RESULT_RECORDED"],
      skippedNotice: "AI zəngi bu demo sessiyasında simulyasiya olunur.",
      steps: [
        {
          id: "ai-call-consent-control",
          title: "Zəng yalnız razılıqla",
          instruction: "Kartda AI zəngi üçün razılıq nəzarəti var: real zəng yalnız təsdiqlənmiş nömrəyə və ayrıca razılıqdan sonra gedir. Açıq demoda növbəti addımdakı zəng simulyasiya olunur.",
          anchor: "lead-voice-permission",
          placement: "top",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: ["leads.card.voice-permission", "leads.card.ai-call"],
          fallback: "AI zəngi bu demoda mövcud deyil; hekayə zəngsiz davam edir.",
          analyticsEvent: "call.consent_shown",
        },
        {
          id: "ai-call-from-card",
          title: "Kartdan zəng edin",
          instruction: "Lid kartında «AI ilə zəng et» düyməsini basın — köməkçi nömrəyə zəng edir, siz isə söhbəti kartda izləyirsiniz.",
          anchor: "lead-ai-call",
          placement: "bottom",
          action: "click",
          targetLabel: "«AI ilə zəng et» basın",
          required: true,
          completion: { kind: "outcome", to: ["CALL_RESULT_RECORDED"] },
          covers: [],
          result: "Zəng bitdi: müddət, nəticə və qeyd kartda və lidin lentində.",
          analyticsEvent: "journey.transition",
        },
      ],
    },
    {
      id: "ai-call-result",
      title: "Zəngin nəticəsi",
      summary: "Zəng necə bitsə də, kartda eyni şey qalır: müddət, nəticə və köməkçinin qeydi — menecer heç nə köçürmür.",
      area: "leads",
      route: "/leads/[id]",
      navGroup: "sales",
      estimatedMinutes: 1,
      requires: [],
      entryStates: ["CALL_RESULT_RECORDED", "CALL_SKIPPED", "CALL_DECLINED", "CALL_NO_ANSWER", "CALL_BUSY", "CALL_BLOCKED", "CALL_FAILED", "CALL_ATTENTION_REQUIRED"],
      exitStates: ["CALL_RESULT_RECORDED", "CALL_SKIPPED", "CALL_DECLINED", "CALL_NO_ANSWER", "CALL_BUSY", "CALL_BLOCKED", "CALL_FAILED", "CALL_ATTENTION_REQUIRED"],
      steps: [
        {
          id: "ai-call-result-card",
          title: "Zəngin nəticəsi kartda",
          instruction: "Zəngin nəticəsi kartda qalır: müddət, nəticə və köməkçinin qeydi. Eyni yazı lidin «Qarşılıqlı əlaqələr» lentinə də düşür.",
          anchor: "lead-call-result",
          placement: "top",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: ["leads.card.call-result"],
          fallback: "Zəng nəticəsi kartın yuxarı hissəsində, razılıq nəzarətinin altındadır.",
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "task",
      title: "Növbəti addım unudulmur",
      summary: "Kvalifikasiyadan sonra sistem özü izləmə tapşırığı yaradır və komandanın lövhəsinə qoyur: kim, nə vaxt, hansı lidlə.",
      area: "tasks",
      route: "/boards/[divisionId]",
      navGroup: "crm",
      estimatedMinutes: 2,
      requires: [],
      entryStates: ["CALL_SKIPPED", "CALL_DECLINED", "CALL_RESULT_RECORDED", "CALL_NO_ANSWER", "CALL_BUSY", "CALL_BLOCKED", "CALL_FAILED", "CALL_ATTENTION_REQUIRED"],
      exitStates: ["TASK_CREATED"],
      intro: { slug: "demo-boards", caption: "Komandanın lövhələri — tapşırıqlar, süzgəclər və hesabatlar.", status: "available" },
      assistantPrompts: ["Tapşırıq niyə avtomatik yarandı?", "Tapşırığı başqasına necə verə bilərəm?"],
      steps: [
        {
          id: "task-boards",
          title: "Komandanın lövhələri",
          instruction: "«Lövhələr» bölməsində hər şöbənin öz iş lövhəsi var. Sizin tapşırığınız satış lövhəsindədir — onu açın.",
          anchor: "boards-index",
          placement: "top",
          action: "click",
          targetLabel: "Lövhəni açın",
          required: true,
          completion: { kind: "snapshot", path: "board.opened", equals: true },
          covers: ["tasks.boards-index", "tasks.board-header", "tasks.board-tabs", "tasks.board-toolbar"],
          result: "Satış lövhəsi açıldı: mərhələ sütunları və kartlar.",
          analyticsEvent: "journey.step_completed",
        },
        {
          id: "task-open",
          title: "Sizin tapşırığınız",
          instruction: "İlk sütunda sizin adınızla yeni kart var — sistem onu kvalifikasiyadan sonra avtomatik yaradıb. Kartı açın.",
          anchor: "board-card",
          placement: "right",
          action: "click",
          targetLabel: "Tapşırığı açın",
          required: true,
          completion: { kind: "transition", to: "TASK_CREATED" },
          covers: ["tasks.board-columns", "tasks.board-card", "tasks.board-card-menu", "tasks.detail.info"],
          result: "Tapşırıq açıldı: məsul — siz, son tarix — sabah, əlaqə — sizin lid.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "task-detail",
          title: "Tapşırığın içi",
          instruction: "Burada status dəyişdirilir, şərh yazılır, lidə bir kliklə keçilir. Kartı sütunlar arasında sürükləmək də olar.",
          anchor: "task-info",
          placement: "left",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["tasks.detail.status", "tasks.detail.comments"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "task-reports",
          title: "Lövhənin hesabatları",
          instruction: "«Hesabatlar» vərəqi: iş yükü, gecikmələr, sürət. Bir tapşırıqla demək olar ki, boşdur — real komandada burada günün mənzərəsi görünür.",
          anchor: "board-reports",
          placement: "top",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["tasks.board-reports"],
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "deal",
      title: "Liddən sövdələşməyə",
      summary: "Lid sövdələşməyə çevrilir və boru xəttində irəliləyir: mərhələ, məbləğ, ehtimal, növbəti addım.",
      area: "deals",
      route: "/deals/[id]",
      navGroup: "sales",
      estimatedMinutes: 4,
      requires: [],
      entryStates: ["TASK_CREATED"],
      exitStates: ["DEAL_ADVANCED"],
      intro: { slug: "deal-detail", caption: "Sövdələşmə kartı — mərhələlər, göstəricilər və lent.", status: "available" },
      assistantPrompts: ["Ehtimal necə hesablanır?", "Mərhələni geri qaytarmaq olar?"],
      steps: [
        {
          id: "deal-convert",
          title: "Lidi çevirin",
          instruction: "Lid kartında «Sövdələşməyə çevir» düyməsini basın.",
          anchor: "leads-convert",
          placement: "bottom",
          action: "confirm",
          targetLabel: "Sövdələşməyə çevirin",
          required: true,
          completion: { kind: "transition", to: "DEAL_CREATED" },
          covers: ["leads.card.convert-dialog"],
          result: "Sövdələşmə yarandı və boru xəttinin ilk mərhələsində göründü.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "deal-board",
          title: "Boru xətti",
          instruction: "Lövhədə hər sütun bir mərhələdir; yuxarıdakı zolaq məbləğləri mərhələlərə görə göstərir. Kartı klikləyin — qısa baxış açılır.",
          anchor: "deals-summary",
          placement: "bottom",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["deals.board.header", "deals.board.summary", "deals.board.list", "deals.board.detail-sheet"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "deal-advance",
          title: "Kartı irəli çəkin",
          instruction: "Öz sövdələşmənizi növbəti mərhələyə sürükləyin.",
          anchor: "deals-kanban",
          placement: "top",
          action: "drag",
          targetLabel: "Növbəti mərhələyə keçirin",
          required: true,
          completion: { kind: "transition", to: "DEAL_ADVANCED" },
          covers: ["deals.board.kanban", "deals.card.stage-progress"],
          result: "Mərhələ dəyişdi; ehtimal və mərhələdə keçirilən günlər yeniləndi.",
          fallback: "Sürükləmə mümkün deyilsə, kartı açıb mərhələ zolağında növbəti mərhələni seçin.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "deal-card",
          title: "Sövdələşmə kartı",
          instruction: "Sövdələşmənin kartı açıldı: solda məbləğ, ehtimal, tarix və məsul; ortada göstərici çipləri və müştəri; aşağıda sürətli hərəkətlər və lent.",
          anchor: "deal-sidebar",
          placement: "right",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: ["deals.card.sidebar", "deals.card.kpi-chips", "deals.card.customer-details", "deals.card.quick-actions", "deals.card.timeline"],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "deal-ai",
          title: "Da Vinci nə deyir",
          instruction: "Sağda AI proqnozu, növbəti addım tövsiyəsi və uyğun təkliflər. Bunlar nümunə nəticələrdir.",
          anchor: "deal-ai-suggestions",
          placement: "left",
          action: "observe",
          required: false,
          completion: { kind: "viewed" },
          covers: ["deals.card.ai-prediction", "deals.card.ai-suggestions", "deals.card.next-best-offers"],
          analyticsEvent: "journey.step_viewed",
        },
      ],
    },
    {
      id: "quote",
      title: "Təklif hazırlayın və göndərin",
      summary: "Kommersiya təklifi sövdələşmədən yaranır: mövqelər, cəm, etibarlılıq müddəti və status — qaralama, göndərilib, baxılıb, qəbul edilib.",
      area: "quotes",
      route: "/quotes/[id]",
      navGroup: "sales",
      estimatedMinutes: 4,
      requires: [],
      entryStates: ["DEAL_ADVANCED"],
      exitStates: ["QUOTE_ACCEPTED"],
      intro: { slug: "quotes", caption: "Kommersiya təklifləri — yaratmaqdan qəbula qədər.", status: "available" },
      assistantPrompts: ["Təklifin müddəti bitsə nə olur?", "Təklifi yenidən göndərmək olar?"],
      steps: [
        {
          id: "quote-create",
          title: "Yeni təklif",
          instruction: "«Yeni təklif» düyməsini basın, sonra pəncərədə «Qaralama yarat».",
          anchor: "quotes-new",
          placement: "bottom",
          action: "confirm",
          targetLabel: "Təklif yaradın",
          required: true,
          completion: { kind: "transition", to: "QUOTE_CREATED" },
          covers: ["quotes.list.header", "quotes.list.filters", "quotes.list.table", "quotes.create-dialog"],
          result: "Təklif nömrə ilə yarandı və sövdələşməyə bağlandı.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "quote-lines",
          title: "Mövqelər və cəm",
          instruction: "Mövqe siyahısında miqdarı dəyişin — cəm və ƏDV dərhal yenilənir. Aşağıda etibarlılıq müddəti.",
          anchor: "quote-line-items",
          placement: "top",
          action: "type",
          targetLabel: "Miqdarı dəyişin",
          required: true,
          completion: { kind: "snapshot", path: "quote.linesEdited", equals: true },
          covers: ["quotes.detail.line-items", "quotes.detail.summary", "quotes.detail.customer", "quotes.detail.header"],
          result: "Cəm yenidən hesablandı.",
          analyticsEvent: "journey.step_completed",
        },
        {
          id: "quote-send",
          title: "Göndərin",
          instruction: "«Göndərilmiş kimi işarələ» düyməsini basın. Demoda e-poçt getmir; status və vaxt möhürü qeyd olunur.",
          anchor: "quote-transition",
          placement: "bottom",
          action: "confirm",
          targetLabel: "«Göndərilmiş kimi işarələ» basın",
          required: true,
          completion: { kind: "transition", to: "QUOTE_SENT" },
          covers: ["quotes.detail.header"],
          result: "Status: göndərilib. Müştəri açanda «baxılıb» olacaq.",
          analyticsEvent: "journey.transition",
        },
        {
          id: "quote-accept",
          title: "Müştəri qəbul edir",
          instruction: "Müştəri rolunda «Qəbul edilmiş kimi işarələ» düyməsini basın — real həyatda bunu müştəri linkdən edir.",
          anchor: "quote-transition",
          placement: "bottom",
          action: "confirm",
          targetLabel: "«Qəbul edilmiş kimi işarələ» basın",
          required: true,
          completion: { kind: "transition", to: "QUOTE_ACCEPTED" },
          covers: ["quotes.detail.header", "quotes.detail.summary"],
          result: "Təklif qəbul edildi; sövdələşmədə bu, lentə düşdü.",
          analyticsEvent: "journey.transition",
        },
      ],
    },
    {
      id: "closed-won",
      title: "Sövdələşmə bağlandı",
      summary: "Qəbul edilmiş təklifdən sonra sövdələşmə qazanılmış mərhələyə keçir — və mənbə kampaniyaya qədər izlənir.",
      area: "deals",
      route: "/deals/[id]",
      navGroup: "sales",
      estimatedMinutes: 1,
      requires: [],
      entryStates: ["QUOTE_ACCEPTED"],
      exitStates: ["CLOSED_WON"],
      steps: [
        {
          id: "closed-won-move",
          title: "Qazanıldı",
          instruction: "Mərhələ zolağında qazanılmış mərhələni seçin və mərhələ yoxlamasını təsdiqləyin.",
          anchor: "deal-stage-progress",
          placement: "bottom",
          action: "choose",
          targetLabel: "«Qazanıldı» mərhələsini seçin",
          required: true,
          completion: { kind: "transition", to: "CLOSED_WON" },
          covers: ["deals.card.stage-progress"],
          result: "Sövdələşmə qazanıldı. Lentdə: kampaniya → dialoq → lid → tapşırıq → təklif → qazanıldı.",
          analyticsEvent: "journey.transition",
        },
      ],
    },
    {
      id: "summary",
      title: "Nə etdiniz və nə oldu",
      summary: "Bir müraciət — bir tam hekayə. Sessiya burada bitir.",
      area: "summary",
      route: "demo:summary",
      navGroup: "demo",
      estimatedMinutes: 1,
      requires: [],
      entryStates: ["CLOSED_WON"],
      exitStates: ["COMPLETED"],
      steps: [
        {
          id: "summary-review",
          title: "Keçdiyiniz yol",
          instruction: "Bu siyahıda tamamladığınız addımlar və hər birinin nəticəsi. Mənbə kampaniya qazanılmış sövdələşməyə bağlıdır.",
          anchor: "journey-summary",
          placement: "auto",
          action: "observe",
          required: true,
          completion: { kind: "viewed" },
          covers: [],
          analyticsEvent: "journey.step_viewed",
        },
        {
          id: "summary-finish",
          title: "Sessiyanı bitirin",
          instruction: "«Bitir» düyməsini basın. Sessiya bağlanır və link bir daha işləmir. Davamı üçün satış komandası ilə əlaqə düyməsi var.",
          anchor: "journey-finish",
          placement: "auto",
          action: "confirm",
          targetLabel: "Demonu bitirin",
          required: true,
          completion: { kind: "transition", to: "COMPLETED" },
          covers: [],
          result: "Demo tamamlandı.",
          analyticsEvent: "journey.completed",
        },
      ],
    },
  ],
}
