ALTER TABLE "mtm_agent_workdays" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mtm_agent_workdays" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "mtm_agent_workdays" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "mtm_agent_workday_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mtm_agent_workday_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "mtm_agent_workday_events" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_site_transitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_site_transitions" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_site_transitions" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_attendance_evidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_attendance_evidence" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_attendance_evidence" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_evidence_assessments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_evidence_assessments" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_evidence_assessments" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_exception_cases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_exception_cases" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_exception_cases" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_timesheet_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_timesheet_approvals" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_timesheet_approvals" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "mtm_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mtm_audit_logs" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "mtm_audit_logs" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "mtm_agents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mtm_agents" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "mtm_agents" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_employee_team_memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_employee_team_memberships" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_employee_team_memberships" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_shift_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_shift_templates" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_shift_templates" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_shift_segments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_shift_segments" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_shift_segments" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_shift_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_shift_assignments" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_shift_assignments" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_shift_default_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_shift_default_assignments" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_shift_default_assignments" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_shift_team_default_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_shift_team_default_assignments" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_shift_team_default_assignments" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_workday_schedule_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_workday_schedule_snapshots" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_workday_schedule_snapshots" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_shift_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_shift_snapshots" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_shift_snapshots" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
ALTER TABLE "workforce_policy_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workforce_policy_snapshots" FORCE ROW LEVEL SECURITY;
CREATE POLICY independent_repo_select ON "workforce_policy_snapshots" FOR SELECT USING ("organizationId" = current_setting('app.org_id', true) OR current_setting('app.rls_bypass', true) = 'on');
