"use client"

/**
 * MTM Alerts — help article (English).
 * Covers only the MTM → Alerts page (GPS anomalies, late starts, missed
 * visits). Alerts are generated by the system — here you only FILTER, READ,
 * RESOLVE or DELETE them; there is NO manual "create alert" action.
 */
import {
  HelpScenario,
  HelpSection,
  HelpStep,
  HelpCallout,
  HelpKey,
  HelpDef,
} from "@/components/help/help-content"

export default function mtmalertsHelpEn() {
  return (
    <div className="space-y-6">
      <HelpScenario
        persona="You're a field-operations supervisor or MTM administrator"
        goal="See every issue raised on your routes — GPS anomalies, late starts, missed visits — in one place, filter to what matters, and mark them resolved as you handle them"
      >
        Reach the page via <HelpKey>MTM</HelpKey> → <HelpKey>Alerts</HelpKey>. You don't create
        alerts yourself — the system raises them automatically from your reps' route activity.
        Every alert is scoped to your organization only. Filtering, search and sort all work over
        the same list, so as you change a filter the stat cards at the top and the count in the
        heading update immediately.
      </HelpScenario>

      <HelpSection title="Səhifədə nə var">
        <p>
          The heading reads <HelpKey>Alerts</HelpKey> with the number of filtered results in
          parentheses (shown as (N)), and below it the line «GPS anomalies, late starts, missed
          visits». Top-right sits a <HelpKey>Show All</HelpKey> / <HelpKey>Hide Resolved</HelpKey>{" "}
          toggle that controls whether resolved alerts appear in the list. Beneath that come four
          stat cards, then the category filter buttons, a search box with a sort selector, and
          finally the alert list itself.
        </p>
        <dl className="rounded-md border p-3">
          <HelpDef term="Total Alerts">The total number of alerts currently loaded.</HelpDef>
          <HelpDef term="Critical">Count of CRITICAL-category alerts (red).</HelpDef>
          <HelpDef term="Warning">Count of WARNING-category alerts (amber).</HelpDef>
          <HelpDef term="Resolved">Count of alerts already marked as resolved.</HelpDef>
          <HelpDef term="Category">Each alert's severity: Critical, Warning or Info — the row colour follows it.</HelpDef>
          <HelpDef term="Agent">The field rep the alert relates to (shown on the right of the row).</HelpDef>
          <HelpDef term="Type">The alert's technical type (shown in monospace at the bottom of the row) — e.g. which rule fired.</HelpDef>
        </dl>
        <p>
          Each alert row is colour-coded by category: critical is red, warning is amber, info is
          blue. On the left of the row is a triangle icon and the alert title; on the right are the
          agent name and a timestamp. If the alert isn't resolved yet, a <HelpKey>Resolve</HelpKey>{" "}
          button appears on the right; if it's already resolved, a green <strong>Resolved</strong>{" "}
          badge takes its place. Far right is a trash-can delete button. When present, a one-line
          description sits under the title, and the alert type is shown at the very bottom.
        </p>
      </HelpSection>

      <HelpSection title="Step by step: filter and find alerts">
        <HelpStep n={1}>
          <p>
            To see just one severity, click one of the category buttons:{" "}
            <HelpKey>All</HelpKey>, <HelpKey>Critical</HelpKey>, <HelpKey>Warning</HelpKey> or{" "}
            <HelpKey>Info</HelpKey>. Each button shows the count for that category in parentheses.
          </p>
          <HelpCallout kind="see" label="What you'll see">
            The selected button becomes filled (highlighted) while the rest stay outlined. The list
            instantly shows only rows of that category, and the (N) count in the heading updates too.
          </HelpCallout>
        </HelpStep>
        <HelpStep n={2}>
          <p>
            To find a specific alert, type into the <HelpKey>Search alerts...</HelpKey> box. The
            search looks at both the alert title and the agent's name.
          </p>
          <HelpCallout kind="see" label="What you'll see">
            The list filters live as you type — only rows whose title or agent name contains that
            text remain. If nothing matches, the «No alerts match the filter» message appears.
          </HelpCallout>
        </HelpStep>
        <HelpStep n={3}>
          <p>
            To change the order, pick <HelpKey>Newest First</HelpKey> or{" "}
            <HelpKey>By Category</HelpKey> from the dropdown on the right.
          </p>
          <HelpCallout kind="see" label="What you'll see">
            «Newest First» puts the most recently raised alerts on top. «By Category» orders rows
            Critical first, then Warning, then Info.
          </HelpCallout>
        </HelpStep>
        <HelpStep n={4}>
          <p>
            To include resolved alerts, click the <HelpKey>Show All</HelpKey> button at the top
            right. To hide them again, the same button now reads <HelpKey>Hide Resolved</HelpKey> —
            click it.
          </p>
          <HelpCallout kind="see" label="What you'll see">
            With «Show All» on, resolved alerts join the list (each with a green{" "}
            <strong>Resolved</strong> badge). By default only unresolved alerts are shown.
          </HelpCallout>
        </HelpStep>
      </HelpSection>

      <HelpSection title="Step by step: resolve or delete an alert">
        <HelpStep n={1}>
          <p>
            Once you've looked into the issue and handled it, click the <HelpKey>Resolve</HelpKey>{" "}
            button on that row (the small button with a check icon).
          </p>
          <HelpCallout kind="see" label="What you'll see">
            An «Alert resolved» toast appears and the list refreshes. In the default filter the alert
            drops out of the list (it now counts as resolved); the <strong>Resolved</strong> stat card
            goes up by one. If you're in «Show All» mode the row stays, but the{" "}
            <HelpKey>Resolve</HelpKey> button is replaced by a green <strong>Resolved</strong> badge.
          </HelpCallout>
        </HelpStep>
        <HelpStep n={2}>
          <p>
            To remove an alert entirely, click the trash-can icon button on the right of the row.
          </p>
          <HelpCallout kind="see" label="What you'll see">
            A «Delete Alert» confirmation dialog opens, naming the alert (by its title) that will be
            deleted. After you confirm, the row leaves the list and the <strong>Total Alerts</strong>{" "}
            card count goes down.
          </HelpCallout>
        </HelpStep>
      </HelpSection>

      <HelpCallout kind="tip">
        <p>
          <HelpKey>Resolve</HelpKey> doesn't delete the alert — it just marks it resolved, so it
          drops out of the default list but is still recoverable via <HelpKey>Show All</HelpKey> and
          kept as a record. If you want an audit trail, choose <HelpKey>Resolve</HelpKey> instead of
          deleting.
        </p>
      </HelpCallout>

      <HelpCallout kind="warning">
        <p>
          Deleting is permanent — a deleted alert is removed from the list for good. If you just want
          to tidy the list, it's safer to close the issue with <HelpKey>Resolve</HelpKey> first.
        </p>
      </HelpCallout>

      <HelpCallout kind="security">
        <p>
          All alerts are scoped to your organization — you only see alerts about your own tenant's
          reps, and you have no access to another organization's alerts.
        </p>
      </HelpCallout>
    </div>
  )
}
